# Generated by Django 3.2.13 on 2022-10-25 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0035_add_auth_providers"),
    ]

    operations = [
        migrations.CreateModel(
            name="SamlAuthProviderModel",
            fields=[
                (
                    "authprovidermodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.authprovidermodel",
                    ),
                ),
                (
                    "metadata",
                    models.TextField(
                        blank=True,
                        help_text="The XML metadata downloaded from the metadata_url.",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="This will be set to True only after a user successfully login with this IdP. This must be True to disable normal username/password login and make SAML the only authentication provider. ",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.authprovidermodel",),
        ),
    ]
