# Generated by Django 3.2.13 on 2022-10-19 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("baserow_enterprise", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("trashed", models.BooleanField(db_index=True, default=False)),
                (
                    "name",
                    models.CharField(
                        help_text="A human friendly name for this team.", max_length=160
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="The group that this team belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="core.group",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "id"),
                "unique_together": {("name", "group")},
            },
        ),
    ]
