# Generated by Django 3.2.13 on 2022-10-28 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_add_auth_providers"),
        ("baserow_enterprise", "0004_add_rbac_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacebookAuthProviderModel",
            fields=[
                (
                    "authprovidermodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.authprovidermodel",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "client_id",
                    models.CharField(
                        help_text="App ID, or consumer key", max_length=191
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        help_text="API secret, client secret, or consumer secret",
                        max_length=191,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.authprovidermodel",),
        ),
        migrations.CreateModel(
            name="GitHubAuthProviderModel",
            fields=[
                (
                    "authprovidermodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.authprovidermodel",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "client_id",
                    models.CharField(
                        help_text="App ID, or consumer key", max_length=191
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        help_text="API secret, client secret, or consumer secret",
                        max_length=191,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.authprovidermodel",),
        ),
        migrations.CreateModel(
            name="GitLabAuthProviderModel",
            fields=[
                (
                    "authprovidermodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.authprovidermodel",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "base_url",
                    models.URLField(help_text="Base URL of the authorization server"),
                ),
                (
                    "client_id",
                    models.CharField(
                        help_text="App ID, or consumer key", max_length=191
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        help_text="API secret, client secret, or consumer secret",
                        max_length=191,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.authprovidermodel",),
        ),
        migrations.CreateModel(
            name="GoogleAuthProviderModel",
            fields=[
                (
                    "authprovidermodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.authprovidermodel",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "client_id",
                    models.CharField(
                        help_text="App ID, or consumer key", max_length=191
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        help_text="API secret, client secret, or consumer secret",
                        max_length=191,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.authprovidermodel",),
        ),
        migrations.CreateModel(
            name="OpenIdConnectAuthProviderModel",
            fields=[
                (
                    "authprovidermodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.authprovidermodel",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "base_url",
                    models.URLField(help_text="Base URL of the authorization server"),
                ),
                (
                    "client_id",
                    models.CharField(
                        help_text="App ID, or consumer key", max_length=191
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        help_text="API secret, client secret, or consumer secret",
                        max_length=191,
                    ),
                ),
                (
                    "authorization_url",
                    models.URLField(help_text="URL to initiate auth flow"),
                ),
                (
                    "access_token_url",
                    models.URLField(help_text="URL to obtain access token"),
                ),
                ("user_info_url", models.URLField(help_text="URL to get user info")),
            ],
            options={
                "abstract": False,
            },
            bases=("core.authprovidermodel",),
        ),
    ]
