# Generated by Django 3.2.13 on 2022-11-16 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0005_oauth2_providers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teamsubject",
            options={"ordering": ("id",)},
        ),
    ]
