# Generated by Django 3.2.13 on 2022-11-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0006_alter_teamsubject_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="teamsubject",
            index=models.Index(
                fields=["-created_on"], name="baserow_ent_created_01fb9f_idx"
            ),
        ),
    ]
