# Generated by Django 3.2.13 on 2022-11-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0008_delete_all_role_assignments"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="roleassignment",
            constraint=models.UniqueConstraint(
                fields=("scope_id", "scope_type", "subject_id", "subject_type"),
                name="subject_and_scope_uniqueness",
            ),
        ),
    ]
