# Generated by Django 3.2.13 on 2023-01-17 10:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0012_rename_team_group"),
    ]

    operations = [
        migrations.RenameField(
            model_name="role",
            old_name="group",
            new_name="workspace",
        ),
    ]
