# Generated by Django 3.2.13 on 2023-02-07 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_auto_20230130_1118"),
        ("baserow_enterprise", "0014_rename_group_roleassignment_workspace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="workspace",
            field=models.ForeignKey(
                help_text="The workspace that this team belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="core.workspace",
            ),
        ),
    ]
