# Generated by Django 3.2.13 on 2023-02-23 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0017_rename_group_name_auditlogentry_workspace_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auditlogexportjob",
            old_name="filter_group_id",
            new_name="filter_workspace_id",
        ),
    ]
