# Generated by Django 3.2.20 on 2023-08-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0020_synced_datetime_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlogentry",
            name="action_uuid",
            field=models.CharField(max_length=36, null=True),
        ),
    ]
