# Generated by Django 3.2.20 on 2023-08-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0021_auditlogentry_action_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlogexportjob",
            name="exclude_columns",
            field=models.CharField(
                help_text="A comma separated list of column names to exclude from the export.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="auditlogentry",
            name="user_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="auditlogentry",
            name="workspace_name",
            field=models.CharField(blank=True, max_length=165, null=True),
        ),
    ]
