# Generated by Django 4.1.13 on 2024-02-27 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0081_usersource_uid"),
        ("builder", "0005_textelement_format"),
        ("baserow_enterprise", "0024_localbaserowpasswordappauthprovider"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthFormElement",
            fields=[
                (
                    "element_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="builder.element",
                    ),
                ),
                (
                    "user_source",
                    models.ForeignKey(
                        help_text="Display the auth form for the selected user source",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.usersource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("builder.element",),
        ),
    ]
