# Generated by Django 5.0.9 on 2024-09-25 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0028_authformelement_login_button_label"),
        (
            "database",
            "0165_datasync_icalcalendardatasync_syncdatasynctablejob_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalBaserowTableDataSync",
            fields=[
                (
                    "datasync_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="database.datasync",
                    ),
                ),
                (
                    "authorized_user",
                    models.ForeignKey(
                        help_text="The user on whose behalf the data is synchronized. The user must have permission to the table.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_table",
                    models.ForeignKey(
                        help_text="The source table containing the data you would like to get the data from.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="database.table",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("database.datasync",),
        ),
    ]
