# Generated by Django 5.0.9 on 2024-11-06 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0031_githubissuesdatasync"),
        ("database", "0171_alter_formview_submit_action_redirect_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitLabIssuesDataSync",
            fields=[
                (
                    "datasync_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="database.datasync",
                    ),
                ),
                (
                    "gitlab_url",
                    models.URLField(
                        default="https://gitlab.com",
                        help_text="The base URL to your GitLab instance (e.g. https://gitlab.com)",
                        max_length=2000,
                    ),
                ),
                (
                    "gitlab_project_id",
                    models.CharField(
                        help_text="The ID of the GitLab project where to sync the issues with.",
                        max_length=255,
                    ),
                ),
                (
                    "gitlab_access_token",
                    models.CharField(
                        help_text="The API access token used to authenticate requests to GitLab.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("database.datasync",),
        ),
    ]
