# Generated by Django 5.0.9 on 2024-12-05 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0033_samlauthprovidermodel_email_attr_key_and_more"),
        ("core", "0093_alter_appauthprovider_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SamlAppAuthProviderModel",
            fields=[
                (
                    "appauthprovider_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.appauthprovider",
                    ),
                ),
                (
                    "metadata",
                    models.TextField(
                        blank=True,
                        help_text="The XML metadata downloaded from the metadata_url.",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="This will be set to True only after a user successfully login with this IdP. This must be True to disable normal username/password login and make SAML the only authentication provider. ",
                    ),
                ),
                (
                    "email_attr_key",
                    models.CharField(
                        db_default="user.email",
                        default="user.email",
                        help_text="The key in the SAML response that contains the email address of the user. If this is not set, the email will be taken from the user's profile.",
                        max_length=32,
                    ),
                ),
                (
                    "first_name_attr_key",
                    models.CharField(
                        db_default="user.first_name",
                        default="user.first_name",
                        help_text="The key in the SAML response that contains the first name of the user. If this is not set, the first name will be taken from the user's profile.",
                        max_length=32,
                    ),
                ),
                (
                    "last_name_attr_key",
                    models.CharField(
                        blank=True,
                        db_default="user.last_name",
                        default="user.last_name",
                        help_text="The key in the SAML response that contains the last name of the user. If this is not set, the last name will be taken from the user's profile.",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
            bases=("core.appauthprovider", models.Model),
        ),
        migrations.AlterModelOptions(
            name="samlauthprovidermodel",
            options={"ordering": ["domain"]},
        ),
    ]
