# Generated by Django 5.0.9 on 2024-12-26 12:08

from django.db import migrations, models

import baserow.contrib.database.views.models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0035_hubspotcontactsdatasync"),
    ]

    operations = [
        migrations.AddField(
            model_name="localbaserowtabledatasync",
            name="source_table_view_id",
            field=models.PositiveIntegerField(
                help_text="If provided, then only the visible fields and rows matching the filters will be synced.",
                null=True,
                verbose_name=baserow.contrib.database.views.models.View,
            ),
        ),
    ]
