# Generated by Django 5.0.9 on 2025-01-14 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0036_localbaserowtabledatasync_source_table_view_id"),
        ("database", "0175_formviewfieldoptions_include_all_select_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodicDataSyncInterval",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_periodic_sync",
                    models.DateTimeField(
                        help_text="Timestamp when the table was last periodically synced.",
                        null=True,
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("MANUAL", "MANUAL"),
                            ("DAILY", "DAILY"),
                            ("HOURLY", "HOURLY"),
                        ],
                        default="MANUAL",
                    ),
                ),
                ("when", models.TimeField()),
                (
                    "automatically_deactivated",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the periodic data sync has been deactivated.",
                    ),
                ),
                (
                    "consecutive_failed_count",
                    models.SmallIntegerField(
                        default=0,
                        help_text="The number of failed sync data sync operations that have failed. This is used to deactivate the periodic sync if it keeps failing.",
                    ),
                ),
                (
                    "authorized_user",
                    models.ForeignKey(
                        help_text="The user on whose behalf the data is periodically synced.Automatically set when the interval changes.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "data_sync",
                    models.OneToOneField(
                        help_text="The periodic data sync.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periodic_interval",
                        to="database.datasync",
                    ),
                ),
            ],
        ),
    ]
