# Generated by Django 5.0.9 on 2025-02-05 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0039_openidconnectappauthprovidermodel"),
        ("dashboard", "0003_widget_dashboarddatasource_summarywidget"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChartWidget",
            fields=[
                (
                    "widget_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dashboard.widget",
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        help_text="Data source for fetching the result to display.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dashboard.dashboarddatasource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("dashboard.widget",),
        ),
    ]
