# Generated by Django 5.0.9 on 2025-02-11 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0040_chartwidget"),
        ("database", "0180_view_allow_public_export"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localbaserowtableserviceaggregationseries",
            name="field",
            field=models.ForeignKey(
                help_text="The aggregated field.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="database.field",
            ),
        ),
    ]
