# Generated by Django 5.0.9 on 2025-03-03 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "baserow_enterprise",
            "0041_alter_localbaserowtableserviceaggregationseries_field",
        ),
        ("core", "0094_alter_importexportresource_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalBaserowTableServiceAggregationSortBy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_on",
                    models.CharField(
                        choices=[
                            ("SERIES", "Series"),
                            ("GROUP_BY", "Group by"),
                            ("PRIMARY", "Primary"),
                        ],
                        max_length=255,
                    ),
                ),
                ("reference", models.CharField(max_length=255)),
                (
                    "direction",
                    models.CharField(
                        choices=[("ASC", "Ascending"), ("DESC", "Descending")],
                        max_length=255,
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "service",
                    models.ForeignKey(
                        help_text="The service which this aggregation series belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_aggregation_sorts",
                        to="core.service",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
    ]
