# Generated by Django 5.0.9 on 2025-04-03 06:13

from django.db import migrations


def migrate_app_labels(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContentType.objects.filter(app_label="baserow_enterprise").filter(
        model__in=[
            "chartwidget",
            "localbaserowgroupedaggregaterows",
            "localbaserowtableserviceaggregationgroupby",
            "localbaserowtableserviceaggregationseries",
            "localbaserowtableserviceaggregationsortby",
        ]
    ).update(app_label="baserow_premium")


class Migration(migrations.Migration):
    dependencies = [
        (
            "baserow_enterprise",
            "0043_remove_localbaserowgroupedaggregaterows_service_ptr_and_more",
        ),
        (
            "baserow_premium",
            "0025_chartwidget_localbaserowgroupedaggregaterows_and_more"
        )
    ]

    operations = [
        migrations.RunPython(migrate_app_labels),
    ]
