# Generated by Django 5.0.13 on 2025-06-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "baserow_enterprise",
            "0047_openidconnectappauthprovidermodel_email_attr_key_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="jiraissuesdatasync",
            name="jira_authentication",
            field=models.CharField(
                choices=[
                    ("API_TOKEN", "API_TOKEN"),
                    ("PERSONAL_ACCESS_TOKEN", "PERSONAL_ACCESS_TOKEN"),
                ],
                db_default="API_TOKEN",
                default="API_TOKEN",
            ),
        ),
        migrations.AlterField(
            model_name="jiraissuesdatasync",
            name="jira_api_token",
            field=models.CharField(
                help_text="The API or personal access token of the Jira account used for authentication.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="jiraissuesdatasync",
            name="jira_username",
            field=models.CharField(
                blank=True,
                help_text="The username of the Jira account used to authenticate. Is only used if the `jira_authentication` is equal `API_TOKEN`",
                max_length=255,
            ),
        ),
    ]
