# Generated by Django 5.0.13 on 2025-05-28 09:27

import django.db.models.deletion
from django.db import migrations, models

import baserow.core.fields


class Migration(migrations.Migration):
    dependencies = [
        (
            "baserow_enterprise",
            "0048_jiraissuesdatasync_jira_authentication_and_more",
        ),
        ("builder", "0057_corehttprequestworkflowaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuilderCustomCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("css", models.TextField(blank=True, help_text="Custom CSS code.")),
                (
                    "js",
                    models.TextField(blank=True, help_text="Custom JavaScript code."),
                ),
                (
                    "builder",
                    baserow.core.fields.AutoOneToOneField(
                        help_text="The builder associated with this custom code.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_code",
                        to="builder.builder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BuilderCustomScript",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("stylesheet", "Stylesheet"),
                            ("javascript", "JavaScript"),
                        ],
                        default="javascript",
                        help_text="The type of script.",
                        max_length=20,
                    ),
                ),
                (
                    "url",
                    models.URLField(blank=True, help_text="The URL of the script."),
                ),
                (
                    "load_type",
                    models.CharField(
                        choices=[("", "None"), ("defer", "Defer"), ("async", "Async")],
                        default="",
                        help_text="The load type of the script.",
                        max_length=10,
                    ),
                ),
                (
                    "crossorigin",
                    models.CharField(
                        choices=[
                            ("", "None"),
                            ("anonymous", "Anonymous"),
                            ("credentials", "Use credentials"),
                        ],
                        default="",
                        help_text="The Crossorigin type of the script.",
                        max_length=20,
                    ),
                ),
                (
                    "builder",
                    models.ForeignKey(
                        help_text="The builder associated with this custom script.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scripts",
                        to="builder.builder",
                    ),
                ),
            ],
        ),
    ]
