# Generated by Django 5.0.13 on 2025-07-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0049_customcode_customscript"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodicdatasyncinterval",
            name="deactivation_reason",
            field=models.CharField(
                choices=[("FAILURE", "FAILURE"), ("LICENSE_UNAVAILABLE", "LICENSE_UNAVAILABLE")],
                help_text="The reason why the periodic data sync was deactivated.",
                max_length=20,
                null=True,
            ),
        ),
    ]
