# Generated by Django 5.0.13 on 2025-09-08 15:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import baserow.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0050_periodicdatasyncinterval_deactivation_reason"),
        ("core", "0101_trashentry_additional_restoration_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique identifier for the chat. Can be provided by the client.",
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="The title of the chat.", max_length=250
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("in_progress", "In progress"),
                            ("canceling", "Canceling"),
                        ],
                        default="idle",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns the chat.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="The workspace the chat belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "workspace", "-updated_on"],
                        name="baserow_ent_user_id_6107b7_idx",
                    )
                ],
            },
        ),
    ]
