# Generated by Django 5.0.13 on 2025-08-21 16:54

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0051_assistantchat"),
        ("database", "0199_field_rules"),
    ]

    operations = [
        migrations.CreateModel(
            name="DateDependency",
            fields=[
                (
                    "fieldrule_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="database.fieldrule",
                    ),
                ),
                (
                    "dependency_linkrow_role",
                    models.CharField(
                        choices=[
                            ("predecessors", "Predecessors"),
                            ("successors", "Successors"),
                        ],
                        default="predecessors",
                        null=True,
                    ),
                ),
                (
                    "dependency_connection_type",
                    models.CharField(
                        choices=[
                            ("end-to-start", "End To Start"),
                            ("end-to-end", "End To End"),
                            ("start-to-end", "Start To End"),
                            ("start-to-start", "Start To Start"),
                        ],
                        default="end-to-start",
                        null=True,
                    ),
                ),
                (
                    "dependency_buffer_type",
                    models.CharField(
                        choices=[
                            ("flexible", "Flexible"),
                            ("fixed", "Fixed"),
                            ("none", "None"),
                        ],
                        default="fixed",
                        null=True,
                    ),
                ),
                (
                    "dependency_buffer",
                    models.DurationField(default=datetime.timedelta(0), null=True),
                ),
                ("include_weekends", models.BooleanField(default=True)),
                (
                    "dependency_linkrow_field",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="database.linkrowfield",
                    ),
                ),
                (
                    "duration_field",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="database.field",
                    ),
                ),
                (
                    "end_date_field",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="database.field",
                    ),
                ),
                (
                    "start_date_field",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="database.field",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("database.fieldrule",),
        ),
    ]
