# Generated by Django 5.0.13 on 2025-09-26 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0052_date_dependency"),
        ("database", "0199_field_rules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datedependency",
            name="dependency_buffer_type",
            field=models.CharField(
                choices=[
                    ("flexible", "Flexible"),
                    ("fixed", "Fixed"),
                    ("none", "None"),
                ],
                default="flexible",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="datedependency",
            name="dependency_linkrow_field",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="database.field",
            ),
        ),
    ]
