# Generated by Django 5.2.16 on 2026-09-07 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0064_fileinputelement_help_text_format_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fileinputelement",
            name="help_text_format",
        ),
        migrations.RemoveField(
            model_name="fileinputelement",
            name="label_format",
        ),
    ]
