from rest_framework.status import HTTP_404_NOT_FOUND


ERROR_GROUP_DOES_NOT_EXIST = (
    'ERROR_GROUP_DOES_NOT_EXIST',
    HTTP_404_NOT_FOUND,
    'The requested group does not exist.'
)
ERROR_USER_NOT_IN_GROUP = 'ERROR_USER_NOT_IN_GROUP'
BAD_TOKEN_SIGNATURE = 'BAD_TOKEN_SIGNATURE'
EXPIRED_TOKEN_SIGNATURE = 'EXPIRED_TOKEN_SIGNATURE'
