# MAKE SURE YOU HAVE SET THE REQUIRED VARIABLES IN the .env FILE.configs:

# This compose file starts up a dev version of the plugin with hot code reloading.
# It is accessible at http://localhost .

services:
  {{ cookiecutter.project_slug }}:
    container_name: {{ cookiecutter.project_slug }}
    image: {{ cookiecutter.project_slug }}_dev
    build:
      dockerfile: ./dev.Dockerfile
      context: .
      args:
        # We allow configuring the PLUGIN_BUILD_UID/PLUGIN_BUILD_GID here so you can run as the dev's actual user
        # reducing the chance the containers screw up the bind mounted folders.
        PLUGIN_BUILD_UID: $PLUGIN_BUILD_UID
        PLUGIN_BUILD_GID: $PLUGIN_BUILD_GID
    ports:
      - "80:80"
      - "443:443"
    environment:
      BASEROW_PUBLIC_URL: http://localhost
    volumes:
      - baserow_data:/baserow/data
      - ./plugins/{{ cookiecutter.project_module }}/backend:/baserow/data/plugins/{{ cookiecutter.project_module }}/backend
      # Override the for node_modules, so we use the node_modules built
      # directly into the image instead of whatever is on your local filesystem.
      - /baserow/data/plugins/{{ cookiecutter.project_module }}/web-frontend/node_modules
      - ./plugins/{{ cookiecutter.project_module }}/web-frontend:/baserow/data/plugins/{{ cookiecutter.project_module }}/web-frontend
    # Open stdin and tty so when attaching key input works as expected.
    stdin_open: true
    tty: true
volumes:
  baserow_data: