FROM node:12

ADD ./baserow /baserow
ADD ./{{ cookiecutter.project_slug }} /{{ cookiecutter.project_slug }}
WORKDIR /{{ cookiecutter.project_slug }}

RUN apt-get update
RUN apt-get -y install make
RUN apt-get -y install curl
RUN apt-get -y install gnupg2

CMD tail -f /dev/null
