# Generated by Django 3.2.13 on 2023-02-10 09:35

import django.db.models.deletion
from django.db import migrations, models

import baserow.core.mixins


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("trashed", models.BooleanField(db_index=True, default=False)),
                ("order", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=255)),
                (
                    "builder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="builder.builder",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "unique_together": {("builder", "name")},
            },
            bases=(baserow.core.mixins.OrderableMixin, models.Model),
        ),
    ]
