# Generated by Django 4.0.10 on 2024-01-17 13:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0001_squashed_0038_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ParagraphElement",
            new_name="TextElement",
        ),
    ]
