# Generated by Django 4.0.10 on 2024-01-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0002_rename_paragraphelement_textelement"),
    ]

    operations = [
        migrations.AddField(
            model_name="headingelement",
            name="alignment",
            field=models.CharField(
                choices=[("left", "Left"), ("center", "Center"), ("right", "Right")],
                default="left",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="textelement",
            name="alignment",
            field=models.CharField(
                choices=[("left", "Left"), ("center", "Center"), ("right", "Right")],
                default="left",
                max_length=10,
            ),
        ),
    ]
