# Generated by Django 3.2.18 on 2023-03-23 08:46

import django.db.models.deletion
from django.db import migrations, models

import baserow.contrib.builder.domains.models
import baserow.core.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0004_element_headingelement_paragraphelement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trashed", models.BooleanField(db_index=True, default=False)),
                ("order", models.PositiveIntegerField()),
                (
                    "domain_name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            baserow.contrib.builder.domains.models.validate_domain
                        ],
                    ),
                ),
                (
                    "builder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="builder.builder",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
            bases=(baserow.core.mixins.OrderableMixin, models.Model),
        ),
    ]
