# Generated by Django 4.0.10 on 2024-01-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0004_image_element_sizing_styles"),
    ]

    operations = [
        migrations.AddField(
            model_name="textelement",
            name="format",
            field=models.CharField(
                choices=[("plain", "Plain"), ("markdown", "Markdown")],
                default="plain",
                help_text="The format of the text",
                max_length=10,
            ),
        ),
    ]
