# Generated by Django 3.2.18 on 2023-03-21 11:16

from django.db import migrations


def forward(apps, schema_editor):
    """
    We have to delete all existing pages because we set `/` as the default path for
    every existing page. The path needs to be unique, so if we have more than 1
    existing page in a builder this migration will fail.
    """

    Page = apps.get_model("builder", "Page")
    Page.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0005_domain"),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]
