# Generated by Django 3.2.18 on 2023-03-21 11:16

from django.db import migrations, models

import baserow.contrib.builder.pages.models  # unimport:skip


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0006_delete_all_pages"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="path",
            field=models.CharField(
                default="/",
                max_length=255,
                validators=[baserow.contrib.builder.pages.validators.path_validation],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="page",
            name="path_params",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterUniqueTogether(
            name="page",
            unique_together={("builder", "name"), ("builder", "path")},
        ),
    ]
