# Generated by Django 3.2.18 on 2023-04-06 09:30

from django.db import migrations


def migrate_params(apps, schema_editor):
    Page = apps.get_model("builder", "Page")
    for page in Page.objects.all():
        old_path_params = page.path_params

        if isinstance(old_path_params, dict):
            page.path_params = [
                {"name": key, "type": value["param_type"]}
                for key, value in old_path_params.items()
            ]
            page.save()


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0007_add_path_to_page"),
    ]

    operations = [
        migrations.RunPython(migrate_params, reverse_code=migrations.RunPython.noop),
    ]
