# Generated by Django 3.2.18 on 2023-04-20 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0067_alter_settings_track_workspace_usage"),
        ("builder", "0008_change_page_params"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="last_published",
            field=models.DateTimeField(
                default=None,
                help_text="Last publication date of this domain",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="published_to",
            field=models.OneToOneField(
                help_text="The published builder.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_from",
                to="builder.builder",
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="builder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domains",
                to="builder.builder",
            ),
        ),
        migrations.CreateModel(
            name="PublishDomainJob",
            fields=[
                (
                    "job_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.job",
                    ),
                ),
                (
                    "user_ip_address",
                    models.GenericIPAddressField(
                        help_text="The user IP address.", null=True
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="builder.domain",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.job", models.Model),
        ),
    ]
