# Generated by Django 3.2.18 on 2023-04-06 13:19

import django.db.models.deletion
from django.db import migrations, models

import baserow.contrib.builder.elements.models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0009_add_domain_publish"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkElement",
            fields=[
                (
                    "element_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="builder.element",
                    ),
                ),
                (
                    "value",
                    baserow.contrib.builder.elements.models.FormulaField(default=""),
                ),
                (
                    "navigation_type",
                    models.CharField(
                        choices=[("page", "Page"), ("custom", "Custom")],
                        default="page",
                        help_text="The navigation type.",
                        max_length=10,
                    ),
                ),
                (
                    "navigate_to_url",
                    baserow.contrib.builder.elements.models.FormulaField(
                        default="",
                        help_text="If no page is selected, this indicate the destination of the link.",
                    ),
                ),
                (
                    "page_parameters",
                    models.JSONField(
                        default=list,
                        help_text="The parameters for each parameters of the selected page if any.",
                    ),
                ),
                (
                    "variant",
                    models.CharField(
                        choices=[("link", "Link"), ("button", "Button")],
                        default="link",
                        help_text="The variant of the link.",
                        max_length=10,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[("self", "Self"), ("blank", "Blank")],
                        default="self",
                        help_text="The target of the link when we click on it.",
                        max_length=10,
                    ),
                ),
                (
                    "width",
                    models.CharField(
                        choices=[("auto", "Auto"), ("full", "Full")],
                        default="auto",
                        max_length=10,
                    ),
                ),
                (
                    "alignment",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("center", "Center"),
                            ("right", "Right"),
                        ],
                        default="left",
                        max_length=10,
                    ),
                ),
                (
                    "navigate_to_page",
                    models.ForeignKey(
                        help_text=(
                            "Destination page id for this link. If null then we use the navigate_to_url property instead.",
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="builder.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("builder.element",),
        ),
    ]
