# Generated by Django 3.2.18 on 2023-06-15 09:55

from django.db import migrations

import baserow.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0010_linkelement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="element",
            name="updated_on",
            field=baserow.core.fields.SyncedDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="updated_on",
            field=baserow.core.fields.SyncedDateTimeField(auto_now=True),
        ),
    ]
