# Generated by Django 4.1.13 on 2024-04-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0010_remove_orphan_collection_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="inputtextelement",
            name="input_type",
            field=models.CharField(
                choices=[("text", "Text"), ("password", "Password")],
                default="text",
                help_text="The type of the input, not applicable for multiline inputs.",
                max_length=10,
                null=True,
            ),
        ),
    ]
