# Generated by Django 4.1.13 on 2024-04-15 07:56

import django.db.models.deletion
from django.db import migrations, models

import baserow.core.formula.field


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0011_inputtextelement_input_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="openpageworkflowaction",
            name="navigate_to_page",
            field=models.ForeignKey(
                help_text=(
                    "Destination page id for this link. If null then we use the navigate_to_url property instead.",
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="builder.page",
            ),
        ),
        migrations.AddField(
            model_name="openpageworkflowaction",
            name="navigate_to_url",
            field=baserow.core.formula.field.FormulaField(
                default="",
                help_text="If no page is selected, this indicate the destination of the link.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="openpageworkflowaction",
            name="navigation_type",
            field=models.CharField(
                choices=[("page", "Page"), ("custom", "Custom")],
                default="page",
                help_text="The navigation type.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="openpageworkflowaction",
            name="page_parameters",
            field=models.JSONField(
                default=list,
                help_text="The parameters for each parameters of the selected page if any.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="openpageworkflowaction",
            name="target",
            field=models.CharField(
                choices=[("self", "Self"), ("blank", "Blank")],
                default="self",
                help_text="The target of the link when we click on it.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="linkelement",
            name="navigate_to_url",
            field=baserow.core.formula.field.FormulaField(
                default="",
                help_text="If no page is selected, this indicate the destination of the link.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="linkelement",
            name="navigation_type",
            field=models.CharField(
                choices=[("page", "Page"), ("custom", "Custom")],
                default="page",
                help_text="The navigation type.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="linkelement",
            name="page_parameters",
            field=models.JSONField(
                default=list,
                help_text="The parameters for each parameters of the selected page if any.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="linkelement",
            name="target",
            field=models.CharField(
                choices=[("self", "Self"), ("blank", "Blank")],
                default="self",
                help_text="The target of the link when we click on it.",
                max_length=10,
                null=True,
            ),
        ),
    ]
