# Generated by Django 3.2.18 on 2023-06-16 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0068_add_user_profile_level_limits"),
        ("builder", "0011_synced_datetime_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageElement",
            fields=[
                (
                    "element_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="builder.element",
                    ),
                ),
                (
                    "image_source_type",
                    models.CharField(
                        choices=[("upload", "Upload"), ("url", "Url")],
                        default="upload",
                        max_length=32,
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="A link to the image file",
                        max_length=1000,
                    ),
                ),
                (
                    "alt_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Text that is displayed when the image can't load",
                    ),
                ),
                (
                    "alignment",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("center", "Center"),
                            ("right", "Right"),
                        ],
                        default="left",
                        max_length=10,
                    ),
                ),
                (
                    "image_file",
                    models.ForeignKey(
                        help_text="An image file uploaded by the user to be used by the element",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="image_element_image_file",
                        to="core.userfile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("builder.element",),
        ),
    ]
