# Generated by Django 3.2.18 on 2023-06-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0013_datasource"),
    ]

    operations = [
        migrations.AddField(
            model_name="element",
            name="style_padding_bottom",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="element",
            name="style_padding_top",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
