# Generated by Django 4.1.13 on 2024-04-23 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0085_workspace_generative_ai_models_settings"),
        ("builder", "0013_auto_20240415_0758"),
    ]

    operations = [
        migrations.AddField(
            model_name="builder",
            name="favicon_file",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="builder_favicon_file",
                to="core.userfile",
            ),
        ),
    ]
