# Generated by Django 3.2.18 on 2023-07-17 07:24

import django.db.models.deletion
from django.db import migrations, models

import baserow.core.formula.field


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0014_initial_styling"),
    ]

    operations = [
        migrations.CreateModel(
            name="InputTextElement",
            fields=[
                (
                    "element_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="builder.element",
                    ),
                ),
                (
                    "default_value",
                    baserow.core.formula.field.FormulaField(
                        default="", help_text="This text input's default value."
                    ),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this text input is a required field.",
                    ),
                ),
                (
                    "placeholder",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The placeholder text which should be applied to the element.",
                        max_length=225,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("builder.element",),
        ),
    ]
