# Generated by Django 3.2.21 on 2023-09-14 13:34

import django.db.models.deletion
from django.db import migrations, models

import baserow.contrib.builder.domains.models


def get_default_domain_content_type_id():
    return baserow.contrib.builder.domains.models.get_default_domain_content_type().id


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("builder", "0017_mainthemeconfigblock"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomDomain",
            fields=[
                (
                    "domain_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="builder.domain",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("builder.domain",),
        ),
        migrations.CreateModel(
            name="SubDomain",
            fields=[
                (
                    "domain_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="builder.domain",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("builder.domain",),
        ),
        migrations.AddField(
            model_name="domain",
            name="content_type",
            field=models.ForeignKey(
                default=get_default_domain_content_type_id,
                on_delete=models.SET(
                    baserow.contrib.builder.domains.models.get_default_domain_content_type
                ),
                related_name="builder_domains",
                to="contenttypes.contenttype",
                verbose_name="content type",
            ),
        ),
    ]
