# Generated by Django 4.1.13 on 2024-05-22 14:50

import uuid

from django.db import migrations, models

from baserow.contrib.database.db.functions import RandomUUID


def gen_uuid(apps, schema_editor):
    """
    Generates the uid for all user sources.
    """

    CollectionField = apps.get_model("builder", "collectionfield")
    CollectionField.objects.update(uid=RandomUUID())


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0019_repeat_element_styling"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionfield",
            name="uid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="builderworkflowaction",
            name="event",
            field=models.CharField(
                help_text="The event that triggers the execution", max_length=60
            ),
        ),
    ]
