# Generated by Django 4.1.13 on 2024-04-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0020_collectionfield_uid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dropdownelement",
            name="multiple",
            field=models.BooleanField(
                default=False,
                help_text="Whether this dropdown allows users to choose multiple values.",
                null=True,
            ),
        ),
    ]
