# Generated by Django 3.2.21 on 2023-09-19 11:12

from django.db import migrations, models

import baserow.contrib.builder.domains.models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("builder", "0020_migrate_existing_domains"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="content_type",
            field=models.ForeignKey(
                on_delete=models.SET(
                    baserow.contrib.builder.domains.models.get_default_domain_content_type
                ),
                related_name="builder_domains",
                to="contenttypes.contenttype",
                verbose_name="content type",
            ),
        ),
    ]
