# Generated by Django 3.2.21 on 2023-09-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0022_collectionelementfield_tableelement"),
    ]

    operations = [
        migrations.AddField(
            model_name="headingelement",
            name="font_color",
            field=models.CharField(
                blank=True,
                default="default",
                help_text="The font color of the heading",
                max_length=20,
            ),
        ),
    ]
