# Generated by Django 4.1.13 on 2024-06-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0023_tableelement_orientation"),
    ]

    operations = [
        migrations.AddField(
            model_name="element",
            name="role_type",
            field=models.CharField(
                choices=[
                    ("allow_all", "Allow All"),
                    ("allow_all_except", "Allow All Except"),
                    ("disallow_all_except", "Disallow All Except"),
                ],
                db_index=True,
                default="allow_all",
                max_length=19,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="element",
            name="roles",
            field=models.JSONField(
                default=list,
                help_text="User roles associated with this element, used in conjunction with role_type.",
                null=True,
            ),
        ),
    ]
