# Generated by Django 3.2.21 on 2023-10-06 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "builder",
            "0024_builderworkflowaction_notificationworkflowaction_openpageworkflowaction",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tableelement",
            name="items_per_page",
            field=models.PositiveIntegerField(
                default=20,
                help_text="The amount item loaded with each page.",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Value cannot be less than 1."
                    ),
                    django.core.validators.MaxValueValidator(
                        100, message="Value cannot be greater than 100."
                    ),
                ],
            ),
        ),
    ]
