# Generated by Django 3.2.21 on 2023-10-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0025_tableelement_items_per_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="element",
            name="style_background",
            field=models.CharField(
                choices=[("none", "None"), ("color", "Color")],
                default="none",
                help_text="What type of background the element should have.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="element",
            name="style_background_color",
            field=models.CharField(
                blank=True,
                default="#ffffffff",
                help_text="The background color if `style_background` is color.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="element",
            name="style_border_bottom_color",
            field=models.CharField(
                blank=True,
                default="border",
                help_text="Bottom border color",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="element",
            name="style_border_bottom_size",
            field=models.PositiveIntegerField(
                default=0, help_text="Pixel height of the bottom border."
            ),
        ),
        migrations.AddField(
            model_name="element",
            name="style_border_top_color",
            field=models.CharField(
                blank=True,
                default="border",
                help_text="Top border color.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="element",
            name="style_border_top_size",
            field=models.PositiveIntegerField(
                default=0, help_text="Pixel height of the top border."
            ),
        ),
        migrations.AddField(
            model_name="element",
            name="style_width",
            field=models.CharField(
                choices=[
                    ("full", "Full"),
                    ("normal", "Normal"),
                    ("medium", "Medium"),
                    ("small", "Small"),
                ],
                default="normal",
                help_text="Indicates the width of the element.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mainthemeconfigblock",
            name="border_color",
            field=models.CharField(default="#d7d8d9ff", max_length=9),
        ),
        migrations.AlterField(
            model_name="element",
            name="style_padding_bottom",
            field=models.PositiveIntegerField(
                default=10, help_text="Padding height of the bottom border."
            ),
        ),
        migrations.AlterField(
            model_name="element",
            name="style_padding_top",
            field=models.PositiveIntegerField(
                default=10, help_text="Padding height of the top border."
            ),
        ),
    ]
