# Generated by Django 4.2.13 on 2024-06-17 15:25

from django.db import migrations, models

import baserow.core.formula.field


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0027_buttonthemeconfigblock_button_border_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="choiceelement",
            name="formula_name",
            field=baserow.core.formula.field.FormulaField(
                default="",
                help_text="The display name of the option if it is a formula",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="choiceelement",
            name="formula_value",
            field=baserow.core.formula.field.FormulaField(
                default="",
                help_text="The value of the option if it is a formula",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="choiceelement",
            name="option_type",
            field=models.CharField(
                choices=[("manual", "Manual"), ("formulas", "Formulas")],
                default="manual",
                max_length=32,
                null=True,
            ),
        ),
    ]
