# Generated by Django 3.2.21 on 2023-10-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0027_collectionelementfield_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionfield",
            name="config",
            field=models.JSONField(
                default=dict, help_text="The configuration of the field."
            ),
        ),
        migrations.AlterField(
            model_name="collectionfield",
            name="type",
            field=models.CharField(help_text="The type of the field.", max_length=225),
        ),
        migrations.AlterField(
            model_name="tableelement",
            name="fields",
            field=models.ManyToManyField(to="builder.CollectionField"),
        ),
        migrations.RemoveField(
            model_name="collectionfield",
            name="value",
        ),
    ]
