# Generated by Django 4.2.13 on 2024-07-17 12:52

import django.db.models.deletion
from django.db import migrations, models

import baserow.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0028_choiceelement_formula_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InputThemeConfigBlock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label_font_family",
                    models.CharField(
                        default="inter",
                        help_text="The font family of the label",
                        max_length=250,
                    ),
                ),
                (
                    "label_text_color",
                    models.CharField(
                        blank=True,
                        default="#070810FF",
                        help_text="The text color of the label",
                        max_length=20,
                    ),
                ),
                (
                    "label_font_size",
                    models.SmallIntegerField(
                        default=13, help_text="The font size of the label"
                    ),
                ),
                (
                    "input_font_family",
                    models.CharField(
                        default="inter",
                        help_text="The font family of the input",
                        max_length=250,
                    ),
                ),
                ("input_font_size", models.SmallIntegerField(default=13)),
                (
                    "input_text_color",
                    models.CharField(
                        blank=True,
                        default="#070810FF",
                        help_text="The text color of the input",
                        max_length=20,
                    ),
                ),
                (
                    "input_background_color",
                    models.CharField(
                        blank=True,
                        default="#FFFFFFFF",
                        help_text="The background color of the input",
                        max_length=20,
                    ),
                ),
                (
                    "input_border_color",
                    models.CharField(
                        blank=True,
                        default="#000000FF",
                        help_text="The color of the input border",
                        max_length=20,
                    ),
                ),
                (
                    "input_border_size",
                    models.SmallIntegerField(default=1, help_text="Input border size"),
                ),
                (
                    "input_border_radius",
                    models.SmallIntegerField(
                        default=0, help_text="Input border radius"
                    ),
                ),
                (
                    "input_vertical_padding",
                    models.SmallIntegerField(
                        default=8, help_text="Input vertical padding"
                    ),
                ),
                (
                    "input_horizontal_padding",
                    models.SmallIntegerField(
                        default=12, help_text="Input horizontal padding"
                    ),
                ),
                (
                    "builder",
                    baserow.core.fields.AutoOneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="builder.builder",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
