# Generated by Django 3.2.21 on 2023-11-28 10:00

from django.db import migrations

import baserow.core.formula.field


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0028_add_collection_field_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="inputtextelement",
            name="label",
            field=baserow.core.formula.field.FormulaField(
                default="", help_text="The text label for this input"
            ),
        ),
    ]
