# Generated by Django 4.2.13 on 2024-07-19 09:46

from django.db import migrations, models

import baserow.core.formula.field


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0030_delete_row_workflow_action"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buttonelement",
            name="alignment",
        ),
        migrations.RemoveField(
            model_name="buttonelement",
            name="button_color",
        ),
        migrations.RemoveField(
            model_name="buttonelement",
            name="width",
        ),
        migrations.RemoveField(
            model_name="formcontainerelement",
            name="button_color",
        ),
        migrations.RemoveField(
            model_name="headingelement",
            name="alignment",
        ),
        migrations.RemoveField(
            model_name="headingelement",
            name="font_color",
        ),
        migrations.RemoveField(
            model_name="imageelement",
            name="alignment",
        ),
        migrations.RemoveField(
            model_name="imageelement",
            name="style_image_constraint",
        ),
        migrations.RemoveField(
            model_name="imageelement",
            name="style_max_height",
        ),
        migrations.RemoveField(
            model_name="imageelement",
            name="style_max_width",
        ),
        migrations.RemoveField(
            model_name="linkelement",
            name="alignment",
        ),
        migrations.RemoveField(
            model_name="linkelement",
            name="button_color",
        ),
        migrations.RemoveField(
            model_name="linkelement",
            name="width",
        ),
        migrations.RemoveField(
            model_name="openpageworkflowaction",
            name="url",
        ),
        migrations.RemoveField(
            model_name="tableelement",
            name="button_color",
        ),
        migrations.RemoveField(
            model_name="textelement",
            name="alignment",
        ),
        migrations.AlterField(
            model_name="choiceelement",
            name="formula_name",
            field=baserow.core.formula.field.FormulaField(
                default="",
                help_text="The display name of the option if it is a formula",
            ),
        ),
        migrations.AlterField(
            model_name="choiceelement",
            name="formula_value",
            field=baserow.core.formula.field.FormulaField(
                default="", help_text="The value of the option if it is a formula"
            ),
        ),
        migrations.AlterField(
            model_name="choiceelement",
            name="multiple",
            field=models.BooleanField(
                default=False,
                help_text="Whether this choice allows users to choose multiple values.",
            ),
        ),
        migrations.AlterField(
            model_name="choiceelement",
            name="option_type",
            field=models.CharField(
                choices=[("manual", "Manual"), ("formulas", "Formulas")],
                default="manual",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="choiceelement",
            name="show_as_dropdown",
            field=models.BooleanField(
                default=True, help_text="Whether to show the choices as a dropdown."
            ),
        ),
        migrations.AlterField(
            model_name="element",
            name="role_type",
            field=models.CharField(
                choices=[
                    ("allow_all", "Allow All"),
                    ("allow_all_except", "Allow All Except"),
                    ("disallow_all_except", "Disallow All Except"),
                ],
                db_index=True,
                default="allow_all",
                max_length=19,
            ),
        ),
        migrations.AlterField(
            model_name="element",
            name="roles",
            field=models.JSONField(
                default=list,
                help_text="User roles associated with this element, used in conjunction with role_type.",
            ),
        ),
        migrations.AlterField(
            model_name="element",
            name="style_background_mode",
            field=models.CharField(
                choices=[("tile", "Tile"), ("fill", "Fill"), ("fit", "Fit")],
                default="fill",
                help_text="The mode of the background image",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="element",
            name="style_margin_bottom",
            field=models.PositiveIntegerField(
                default=0, help_text="Margin size of the bottom border."
            ),
        ),
        migrations.AlterField(
            model_name="element",
            name="style_margin_left",
            field=models.PositiveIntegerField(
                default=0, help_text="Margin size of the left border."
            ),
        ),
        migrations.AlterField(
            model_name="element",
            name="style_margin_right",
            field=models.PositiveIntegerField(
                default=0, help_text="Margin size of the right border."
            ),
        ),
        migrations.AlterField(
            model_name="element",
            name="style_margin_top",
            field=models.PositiveIntegerField(
                default=0, help_text="Margin size of the top border."
            ),
        ),
        migrations.AlterField(
            model_name="element",
            name="styles",
            field=models.JSONField(
                default=dict, help_text="The theme overrides for this element"
            ),
        ),
        migrations.AlterField(
            model_name="inputtextelement",
            name="input_type",
            field=models.CharField(
                choices=[("text", "Text"), ("password", "Password")],
                default="text",
                help_text="The type of the input, not applicable for multiline inputs.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="repeatelement",
            name="button_load_more_label",
            field=baserow.core.formula.field.FormulaField(
                blank=True, default="", help_text="The label of the show more button"
            ),
        ),
        migrations.AlterField(
            model_name="tableelement",
            name="button_load_more_label",
            field=baserow.core.formula.field.FormulaField(
                blank=True, default="", help_text="The label of the show more button"
            ),
        ),
        migrations.DeleteModel(
            name="MainThemeConfigBlock",
        ),
    ]
