# Generated by Django 3.2.21 on 2023-12-15 10:41

from django.db import migrations, models

import baserow.core.formula.field


class Migration(migrations.Migration):
    dependencies = [
        (
            "builder",
            "0032_localbaserowcreaterowworkflowaction_localbaserowupdaterowworkflowaction",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="builderworkflowaction",
            name="event",
            field=models.CharField(
                choices=[("click", "Click"), ("submit", "Submit")],
                help_text="The event that triggers the execution",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="imageelement",
            name="alt_text",
            field=baserow.core.formula.field.FormulaField(
                blank=True,
                default="",
                help_text="Text that is displayed when the image can't load",
            ),
        ),
        migrations.AlterField(
            model_name="imageelement",
            name="image_url",
            field=baserow.core.formula.field.FormulaField(
                blank=True,
                default="",
                help_text="A link to the image file",
                max_length=1000,
            ),
        ),
    ]
