# Generated by Django 4.2.13 on 2024-08-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0033_collectionfield_styles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choiceelementoption",
            name="value",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The value of the option. An empty string is a valid value. When the value field is null, the frontend will auto-populate the value using the name field.",
                null=True,
            ),
        ),
    ]
