# Generated by Django 4.2.13 on 2024-08-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0034_alter_choiceelementoption_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="repeatelement",
            name="schema_property",
            field=models.CharField(
                help_text="A multiple valued schema property to use for the data source.",
                max_length=225,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tableelement",
            name="schema_property",
            field=models.CharField(
                help_text="A multiple valued schema property to use for the data source.",
                max_length=225,
                null=True,
            ),
        ),
    ]
