# Generated by Django 4.2.13 on 2024-09-09 09:50

from django.db import migrations, models


def create_missing_shared_page(apps, schema_editor):
    Builder = apps.get_model("builder", "builder")
    Page = apps.get_model("builder", "page")

    # An update in case we have imported a template with a shared page
    Page.objects.filter(path="__shared__").update(shared=True)

    pages_to_create = []
    for builder in Builder.objects.exclude(page__in=Page.objects.filter(shared=True)):
        pages_to_create.append(
            Page(
                builder=builder,
                name="__shared__",
                path="__shared__",
                shared=True,
                order=0,
            )
        )

    Page.objects.bulk_create(pages_to_create, batch_size=100)


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0038_collection_element_property_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="shared",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterModelOptions(
            name="page",
            options={"ordering": ("-shared", "order")},
        ),
        migrations.AlterModelOptions(
            name="datasource",
            options={"ordering": ("page_id", "order", "id")},
        ),
        migrations.RunPython(
            create_missing_shared_page,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
