# Generated by Django 5.0.9 on 2024-11-26 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0040_datetimepickerelement"),
    ]

    operations = [
        migrations.AddField(
            model_name="builder",
            name="login_page",
            field=models.OneToOneField(
                help_text="The login page for this application. This is related to the visibility settings of builder pages.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="login_page",
                to="builder.page",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="role_type",
            field=models.CharField(
                choices=[
                    ("allow_all", "Allow All"),
                    ("allow_all_except", "Allow All Except"),
                    ("disallow_all_except", "Disallow All Except"),
                ],
                db_default="allow_all",
                db_index=True,
                default="allow_all",
                help_text="Role type is used in conjunction with roles to control access to this page.",
                max_length=19,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="roles",
            field=models.JSONField(
                db_default=[],
                default=list,
                help_text="List of user roles that are associated with this page. Used in conjunction with role_type.",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="visibility",
            field=models.CharField(
                choices=[("all", "All"), ("logged-in", "Logged In")],
                db_default="all",
                db_index=True,
                default="all",
                help_text="Controls the page's visibility. When set to 'logged-in', the builder's login_page must also be set.",
                max_length=20,
            ),
        ),
    ]
