# Generated by Django 5.0.9 on 2024-10-17 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0041_builder_login_page_page_role_type_page_roles_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterElement",
            fields=[
                (
                    "element_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="builder.element",
                    ),
                ),
                (
                    "share_type",
                    models.CharField(
                        choices=[
                            ("all", "All"),
                            ("only", "Only"),
                            ("except", "Except"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                ("pages", models.ManyToManyField(blank=True, to="builder.page")),
            ],
            options={
                "abstract": False,
            },
            bases=("builder.element",),
        ),
        migrations.CreateModel(
            name="HeaderElement",
            fields=[
                (
                    "element_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="builder.element",
                    ),
                ),
                (
                    "share_type",
                    models.CharField(
                        choices=[
                            ("all", "All"),
                            ("only", "Only"),
                            ("except", "Except"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                ("pages", models.ManyToManyField(blank=True, to="builder.page")),
            ],
            options={
                "abstract": False,
            },
            bases=("builder.element",),
        ),
    ]
