# Generated by Django 5.0.9 on 2025-01-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0044_colorthemeconfigblock_custom_colors"),
    ]

    operations = [
        migrations.AddField(
            model_name="element",
            name="style_background_radius",
            field=models.SmallIntegerField(
                db_default=0, default=0, help_text="Background radius."
            ),
        ),
        migrations.AddField(
            model_name="element",
            name="style_border_radius",
            field=models.SmallIntegerField(
                db_default=0, default=0, help_text="Border radius."
            ),
        ),
    ]
