# Generated by Django 5.0.9 on 2025-01-15 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0045_element_style_background_radius_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagethemeconfigblock",
            name="image_border_radius",
            field=models.SmallIntegerField(
                db_default=0,
                default=0,
                help_text="The border radius for this image element.",
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Value cannot be less than 0."
                    ),
                    django.core.validators.MaxValueValidator(
                        100, message="Value cannot be greater than 100."
                    ),
                ],
            ),
        ),
    ]
