# Generated by Django 5.0.9 on 2025-01-16 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0046_imagethemeconfigblock_image_radius"),
    ]

    operations = [
        migrations.AddField(
            model_name="repeatelement",
            name="horizontal_gap",
            field=models.IntegerField(
                db_default=0,
                default=0,
                help_text="The amount of horizontal space between repeat elements.",
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Value cannot be less than 0."
                    ),
                    django.core.validators.MaxValueValidator(
                        2000, message="Value cannot be greater than 2000."
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="repeatelement",
            name="vertical_gap",
            field=models.IntegerField(
                db_default=0,
                default=0,
                help_text="The amount of vertical space between repeat elements.",
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Value cannot be less than 0."
                    ),
                    django.core.validators.MaxValueValidator(
                        2000, message="Value cannot be greater than 2000."
                    ),
                ],
            ),
        ),
    ]
