# Generated by Django 5.0.9 on 2025-01-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "builder",
            "0048_alter_buttonthemeconfigblock_button_background_color_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="element",
            name="style_width_child",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("medium", "Medium"),
                    ("small", "Small"),
                ],
                db_default="normal",
                default="normal",
                help_text="Indicates the width of the child element.",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="element",
            name="style_width",
            field=models.CharField(
                choices=[
                    ("full", "Full"),
                    ("full-width", "Full Width"),
                    ("normal", "Normal"),
                    ("medium", "Medium"),
                    ("small", "Small"),
                ],
                default="normal",
                help_text="Indicates the width of the root element.",
                max_length=20,
            ),
        ),
    ]
