# Generated by Django 5.0.9 on 2025-03-05 10:12

import django.db.models.deletion
from django.db import migrations, models

import baserow.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0052_menuitemelement_menuelement"),
    ]

    operations = [
        migrations.AddField(
            model_name="buttonthemeconfigblock",
            name="button_active_background_color",
            field=models.CharField(
                blank=True,
                default="#4783db",
                help_text="The background color of buttons when active",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="buttonthemeconfigblock",
            name="button_active_border_color",
            field=models.CharField(
                blank=True,
                default="#275d9f",
                help_text="The border color of buttons when active",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="buttonthemeconfigblock",
            name="button_active_text_color",
            field=models.CharField(
                blank=True,
                default="#ffffffff",
                help_text="The text color of buttons when active",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="linkthemeconfigblock",
            name="link_active_text_color",
            field=models.CharField(
                blank=True,
                default="#275d9f",
                help_text="The hover color of links when active",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="menuelement",
            name="alignment",
            field=models.CharField(
                choices=[("left", "Left"), ("center", "Center"), ("right", "Right")],
                default="left",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="MenuThemeConfigBlock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "button_font_family",
                    models.CharField(default="inter", max_length=250),
                ),
                ("button_font_size", models.SmallIntegerField(default=13)),
                (
                    "button_font_weight",
                    models.CharField(
                        choices=[
                            ("thin", "Thin"),
                            ("extra-light", "Extra Light"),
                            ("light", "Light"),
                            ("regular", "Regular"),
                            ("medium", "Medium"),
                            ("semi-bold", "Semi Bold"),
                            ("bold", "Bold"),
                            ("extra-bold", "Extra Bold"),
                            ("heavy", "Heavy"),
                            ("black", "Black"),
                            ("extra-black", "Extra Black"),
                        ],
                        db_default="regular",
                        default="regular",
                        max_length=11,
                    ),
                ),
                (
                    "button_alignment",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("center", "Center"),
                            ("right", "Right"),
                        ],
                        default="left",
                        max_length=10,
                    ),
                ),
                (
                    "button_text_alignment",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("center", "Center"),
                            ("right", "Right"),
                        ],
                        default="center",
                        max_length=10,
                    ),
                ),
                (
                    "button_width",
                    models.CharField(
                        choices=[("auto", "Auto"), ("full", "Full")],
                        default="auto",
                        max_length=10,
                    ),
                ),
                (
                    "button_background_color",
                    models.CharField(
                        blank=True,
                        default="primary",
                        help_text="The background color of buttons",
                        max_length=255,
                    ),
                ),
                (
                    "button_text_color",
                    models.CharField(
                        blank=True,
                        default="#ffffffff",
                        help_text="The text color of buttons",
                        max_length=255,
                    ),
                ),
                (
                    "button_border_color",
                    models.CharField(
                        blank=True,
                        default="border",
                        help_text="The border color of buttons",
                        max_length=255,
                    ),
                ),
                (
                    "button_border_size",
                    models.SmallIntegerField(default=0, help_text="Button border size"),
                ),
                (
                    "button_border_radius",
                    models.SmallIntegerField(
                        default=4, help_text="Button border radius"
                    ),
                ),
                (
                    "button_vertical_padding",
                    models.SmallIntegerField(
                        default=12, help_text="Button vertical padding"
                    ),
                ),
                (
                    "button_horizontal_padding",
                    models.SmallIntegerField(
                        default=12, help_text="Button horizontal padding"
                    ),
                ),
                (
                    "button_hover_background_color",
                    models.CharField(
                        blank=True,
                        default="#96baf6ff",
                        help_text="The background color of buttons when hovered",
                        max_length=255,
                    ),
                ),
                (
                    "button_hover_text_color",
                    models.CharField(
                        blank=True,
                        default="#ffffffff",
                        help_text="The text color of buttons when hovered",
                        max_length=255,
                    ),
                ),
                (
                    "button_hover_border_color",
                    models.CharField(
                        blank=True,
                        default="border",
                        help_text="The border color of buttons when hovered",
                        max_length=255,
                    ),
                ),
                (
                    "button_active_background_color",
                    models.CharField(
                        blank=True,
                        default="#4783db",
                        help_text="The background color of buttons when active",
                        max_length=255,
                    ),
                ),
                (
                    "button_active_text_color",
                    models.CharField(
                        blank=True,
                        default="#ffffffff",
                        help_text="The text color of buttons when active",
                        max_length=255,
                    ),
                ),
                (
                    "button_active_border_color",
                    models.CharField(
                        blank=True,
                        default="#275d9f",
                        help_text="The border color of buttons when active",
                        max_length=255,
                    ),
                ),
                ("link_font_family", models.CharField(default="inter", max_length=250)),
                ("link_font_size", models.SmallIntegerField(default=13)),
                (
                    "link_font_weight",
                    models.CharField(
                        choices=[
                            ("thin", "Thin"),
                            ("extra-light", "Extra Light"),
                            ("light", "Light"),
                            ("regular", "Regular"),
                            ("medium", "Medium"),
                            ("semi-bold", "Semi Bold"),
                            ("bold", "Bold"),
                            ("extra-bold", "Extra Bold"),
                            ("heavy", "Heavy"),
                            ("black", "Black"),
                            ("extra-black", "Extra Black"),
                        ],
                        db_default="regular",
                        default="regular",
                        max_length=11,
                    ),
                ),
                (
                    "link_text_alignment",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("center", "Center"),
                            ("right", "Right"),
                        ],
                        default="left",
                        max_length=10,
                    ),
                ),
                (
                    "link_text_color",
                    models.CharField(
                        blank=True,
                        default="primary",
                        help_text="The text color of links",
                        max_length=255,
                    ),
                ),
                (
                    "link_hover_text_color",
                    models.CharField(
                        blank=True,
                        default="#96baf6ff",
                        help_text="The hover color of links when hovered",
                        max_length=255,
                    ),
                ),
                (
                    "link_active_text_color",
                    models.CharField(
                        blank=True,
                        default="#275d9f",
                        help_text="The hover color of links when active",
                        max_length=255,
                    ),
                ),
                (
                    "builder",
                    baserow.core.fields.AutoOneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="builder.builder",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
