# Generated by Django 5.0.9 on 2025-03-18 13:03

from django.db import migrations

import baserow.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0054_simplecontainerelement"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkthemeconfigblock",
            name="link_active_text_decoration",
            field=baserow.core.fields.MultipleFlagField(
                db_default="1000",
                default="1000",
                help_text="The text decoration flags [underline, strike, uppercase, italic]",
                max_length=4,
                num_flags=4,
            ),
        ),
        migrations.AddField(
            model_name="linkthemeconfigblock",
            name="link_default_text_decoration",
            field=baserow.core.fields.MultipleFlagField(
                db_default="1000",
                default="1000",
                help_text="The text decoration flags [underline, strike, uppercase, italic]",
                max_length=4,
                num_flags=4,
            ),
        ),
        migrations.AddField(
            model_name="linkthemeconfigblock",
            name="link_hover_text_decoration",
            field=baserow.core.fields.MultipleFlagField(
                db_default="1000",
                default="1000",
                help_text="The text decoration flags [underline, strike, uppercase, italic]",
                max_length=4,
                num_flags=4,
            ),
        ),
        migrations.AddField(
            model_name="typographythemeconfigblock",
            name="heading_1_text_decoration",
            field=baserow.core.fields.MultipleFlagField(
                db_default="0000",
                default="0000",
                help_text="The text decoration flags [underline, strike, uppercase, italic]",
                max_length=4,
                num_flags=4,
            ),
        ),
        migrations.AddField(
            model_name="typographythemeconfigblock",
            name="heading_2_text_decoration",
            field=baserow.core.fields.MultipleFlagField(
                db_default="0000",
                default="0000",
                help_text="The text decoration flags [underline, strike, uppercase, italic]",
                max_length=4,
                num_flags=4,
            ),
        ),
        migrations.AddField(
            model_name="typographythemeconfigblock",
            name="heading_3_text_decoration",
            field=baserow.core.fields.MultipleFlagField(
                db_default="0000",
                default="0000",
                help_text="The text decoration flags [underline, strike, uppercase, italic]",
                max_length=4,
                num_flags=4,
            ),
        ),
        migrations.AddField(
            model_name="typographythemeconfigblock",
            name="heading_4_text_decoration",
            field=baserow.core.fields.MultipleFlagField(
                db_default="0000",
                default="0000",
                help_text="The text decoration flags [underline, strike, uppercase, italic]",
                max_length=4,
                num_flags=4,
            ),
        ),
        migrations.AddField(
            model_name="typographythemeconfigblock",
            name="heading_5_text_decoration",
            field=baserow.core.fields.MultipleFlagField(
                db_default="0000",
                default="0000",
                help_text="The text decoration flags [underline, strike, uppercase, italic]",
                max_length=4,
                num_flags=4,
            ),
        ),
        migrations.AddField(
            model_name="typographythemeconfigblock",
            name="heading_6_text_decoration",
            field=baserow.core.fields.MultipleFlagField(
                db_default="0000",
                default="0000",
                help_text="The text decoration flags [underline, strike, uppercase, italic]",
                max_length=4,
                num_flags=4,
            ),
        ),
        migrations.DeleteModel(
            name="MenuThemeConfigBlock",
        ),
    ]
