# Generated by Django 5.0.9 on 2025-03-19 15:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import baserow.core.formula.field


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0055_linkthemeconfigblock_link_active_text_decoration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RatingElement",
            fields=[
                (
                    "element_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="builder.element",
                    ),
                ),
                ("value", baserow.core.formula.field.FormulaField(default="")),
                (
                    "max_value",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Maximum value the rating can take.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="primary",
                        help_text="Color of the symbols.",
                        max_length=50,
                    ),
                ),
                (
                    "rating_style",
                    models.CharField(
                        choices=[
                            ("star", "Star"),
                            ("heart", "Heart"),
                            ("thumbs-up", "Thumbs Up"),
                            ("flag", "Flag"),
                            ("smile", "Smile"),
                        ],
                        default="star",
                        help_text="Rating style. Allowed values: star, heart, thumbs-up, flag, smile.",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("builder.element",),
        ),
        migrations.CreateModel(
            name="RatingInputElement",
            fields=[
                (
                    "element_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="builder.element",
                    ),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this form element is a required field.",
                    ),
                ),
                ("value", baserow.core.formula.field.FormulaField(default="")),
                (
                    "max_value",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Maximum value the rating can take.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="primary",
                        help_text="Color of the symbols.",
                        max_length=50,
                    ),
                ),
                (
                    "rating_style",
                    models.CharField(
                        choices=[
                            ("star", "Star"),
                            ("heart", "Heart"),
                            ("thumbs-up", "Thumbs Up"),
                            ("flag", "Flag"),
                            ("smile", "Smile"),
                        ],
                        default="star",
                        help_text="Rating style. Allowed values: star, heart, thumbs-up, flag, smile.",
                        max_length=50,
                    ),
                ),
                (
                    "label",
                    baserow.core.formula.field.FormulaField(
                        default="", help_text="The text label for this field"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("builder.element",),
        ),
    ]
