# Generated by Django 5.0.13 on 2025-06-13 15:33

from django.db import migrations


def remove_dandling_builders(apps, schema_editor):
    Builder = apps.get_model("builder", "Builder")
    UserSource = apps.get_model("core", "UserSource")
    builder_to_patch = Builder.objects.filter(
        workspace=None, published_from=None, snapshot_from=None
    )
    for user_source in UserSource.objects.filter(application_id__in=builder_to_patch):
        user_source.uid = f"conflict_{user_source.uid}"
        user_source.save()

    print(f"\n{builder_to_patch.count()} dandling builder applications patched\n")


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0057_corehttprequestworkflowaction"),
    ]

    operations = [
        migrations.RunPython(
            remove_dandling_builders, reverse_code=migrations.RunPython.noop
        ),
    ]
