# Generated by Django 5.0.13 on 2025-06-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0058_delete_uid_from_dandling_applications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionfield",
            name="name",
            field=models.CharField(
                blank=True, help_text="The name of the field.", max_length=225
            ),
        ),
    ]
