# Generated by Django 5.0.13 on 2025-06-12 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0059_alter_collectionfield_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordselectorelement",
            name="items_per_page",
            field=models.PositiveIntegerField(
                default=20,
                help_text="The amount item loaded with each page.",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Value cannot be less than 1."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="repeatelement",
            name="items_per_page",
            field=models.PositiveIntegerField(
                default=20,
                help_text="The amount item loaded with each page.",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Value cannot be less than 1."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tableelement",
            name="items_per_page",
            field=models.PositiveIntegerField(
                default=20,
                help_text="The amount item loaded with each page.",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Value cannot be less than 1."
                    )
                ],
            ),
        ),
    ]
