# Generated by Django 5.0.13 on 2025-07-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0061_coresmtpemailworkflowaction"),
        ("core", "0100_auto_20250610_1917"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="datasource",
            index=models.Index(
                fields=["page_id", "order", "id"], name="builder_dat_page_id_5f7455_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(
                fields=["-shared", "order"], name="builder_pag_shared_9280eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(
                fields=["builder", "-shared", "order"],
                name="builder_pag_builder_da0520_idx",
            ),
        ),
    ]
