# Generated by Django 5.0.13 on 2025-08-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0062_datasource_builder_dat_page_id_5f7455_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="element",
            name="css_classes",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="The additional CSS classes for this element.",
                max_length=255,
            ),
        ),
    ]
