# Generated by Django 5.2.15 on 2026-07-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0074_corestartworkflowworkflowaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='builderworkflowaction',
            name='trashed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
