# Generated by Django 5.2.15 on 2026-07-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0076_iframeelement_allow_same_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='builderworkflowaction',
            name='trashed',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AlterUniqueTogether(
            name='datasource',
            unique_together=set(),
        ),
    ]
