# Generated by Django 5.2.15 on 2026-07-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0077_builderworkflowaction_trashed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datasource',
            unique_together=set(),
        ),
    ]
