# Generated by Django 5.2.16 on 2026-09-07 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0078_checkboxelement_label_format_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkboxelement",
            name="label_format",
        ),
        migrations.RemoveField(
            model_name="choiceelement",
            name="label_format",
        ),
        migrations.RemoveField(
            model_name="choiceelement",
            name="option_format",
        ),
        migrations.RemoveField(
            model_name="collectionfield",
            name="name_format",
        ),
        migrations.RemoveField(
            model_name="datetimepickerelement",
            name="label_format",
        ),
        migrations.RemoveField(
            model_name="inputtextelement",
            name="label_format",
        ),
        migrations.RemoveField(
            model_name="notificationworkflowaction",
            name="description_format",
        ),
        migrations.RemoveField(
            model_name="notificationworkflowaction",
            name="title_format",
        ),
        migrations.RemoveField(
            model_name="ratinginputelement",
            name="label_format",
        ),
        migrations.RemoveField(
            model_name="recordselectorelement",
            name="label_format",
        ),
    ]
