# Generated by Django 5.2.16 on 2026-09-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0079_remove_text_format_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='choiceelement',
            name='option_format',
            field=models.CharField(choices=[('plain', 'Plain'), ('markdown', 'Markdown')], db_default='plain', default='plain', help_text='The format of the option names, for both manual and formula options.', max_length=10),
        ),
        migrations.AddField(
            model_name='collectionfield',
            name='name_format',
            field=models.CharField(choices=[('plain', 'Plain'), ('markdown', 'Markdown')], db_default='plain', default='plain', help_text='The format of the field name.', max_length=10),
        ),
    ]
