from baserow.contrib.database.operations import (
    CreateTableDatabaseTableOperationType,
    ListTablesDatabaseTableOperationType,
)
from baserow.contrib.database.rows.operations import (
    DeleteDatabaseRowOperationType,
    ReadDatabaseRowOperationType,
    UpdateDatabaseRowOperationType,
)
from baserow.contrib.database.table.operations import (
    CreateRowDatabaseTableOperationType,
    DeleteDatabaseTableOperationType,
    ListRowsDatabaseTableOperationType,
    ReadDatabaseTableOperationType,
    UpdateDatabaseTableOperationType,
)
from baserow.core.operations import (
    DeleteGroupOperationType,
    ListApplicationsGroupOperationType,
    ReadApplicationOperationType,
    ReadGroupOperationType,
    UpdateGroupOperationType,
)

default_roles = {
    "admin": [
        ReadGroupOperationType,
        UpdateGroupOperationType,
        DeleteGroupOperationType,
        ListApplicationsGroupOperationType,
        ListTablesDatabaseTableOperationType,
        CreateTableDatabaseTableOperationType,
        ReadApplicationOperationType,
        ReadDatabaseTableOperationType,
        UpdateDatabaseTableOperationType,
        DeleteDatabaseTableOperationType,
        ListRowsDatabaseTableOperationType,
        CreateRowDatabaseTableOperationType,
        ReadDatabaseRowOperationType,
        UpdateDatabaseRowOperationType,
        DeleteDatabaseRowOperationType,
    ],
    "builder": [
        ReadGroupOperationType,
        ListApplicationsGroupOperationType,
        ListTablesDatabaseTableOperationType,
        CreateTableDatabaseTableOperationType,
        ReadApplicationOperationType,
        ReadDatabaseTableOperationType,
        UpdateDatabaseTableOperationType,
        DeleteDatabaseTableOperationType,
        ListRowsDatabaseTableOperationType,
        CreateRowDatabaseTableOperationType,
        ReadDatabaseRowOperationType,
        UpdateDatabaseRowOperationType,
        DeleteDatabaseRowOperationType,
    ],
    "editor": [
        ReadGroupOperationType,
        ListApplicationsGroupOperationType,
        ListTablesDatabaseTableOperationType,
        ReadApplicationOperationType,
        ReadDatabaseTableOperationType,
        ListRowsDatabaseTableOperationType,
        CreateRowDatabaseTableOperationType,
        ReadDatabaseRowOperationType,
        UpdateDatabaseRowOperationType,
        DeleteDatabaseRowOperationType,
    ],
    "commenter": [
        ReadGroupOperationType,
        ListApplicationsGroupOperationType,
        ListTablesDatabaseTableOperationType,
        ReadApplicationOperationType,
        ReadDatabaseTableOperationType,
        ListRowsDatabaseTableOperationType,
        ReadDatabaseRowOperationType,
    ],
    "viewer": [
        ReadGroupOperationType,
        ListApplicationsGroupOperationType,
        ListTablesDatabaseTableOperationType,
        ReadApplicationOperationType,
        ReadDatabaseTableOperationType,
        ListRowsDatabaseTableOperationType,
        ReadDatabaseRowOperationType,
    ],
    "no_role": [],
}
