FROM node:10

ADD . /web-frontend

WORKDIR /web-frontend

RUN apt-get update
RUN apt-get -y install make
RUN apt-get -y install curl
RUN apt-get -y install gnupg2

RUN make install-dependencies
RUN yarn install
RUN yarn run build

ENTRYPOINT yarn run demo
