# Generated by Django 5.0.13 on 2025-04-04 09:04

import django.db.models.deletion
from django.db import migrations, models

import baserow.core.fields
import baserow.core.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0001_initial"),
        ("core", "0097_userprofile_completed_guided_tours"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationWorkflow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                ("trashed", models.BooleanField(db_index=True, default=False)),
                ("name", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField()),
                (
                    "automation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="automation.automation",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "unique_together": {("automation", "name")},
            },
            bases=(models.Model, baserow.core.mixins.OrderableMixin),
        ),
        migrations.CreateModel(
            name="DuplicateAutomationWorkflowJob",
            fields=[
                (
                    "job_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.job",
                    ),
                ),
                (
                    "user_ip_address",
                    models.GenericIPAddressField(
                        help_text="The user IP address.", null=True
                    ),
                ),
                (
                    "user_websocket_id",
                    models.CharField(
                        help_text="The user websocket uuid needed to manage signals sent correctly.",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "user_session_id",
                    models.CharField(
                        help_text="The user session uuid needed for undo/redo functionality.",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "user_action_group_id",
                    models.CharField(
                        help_text="The user session uuid needed for undo/redo action group functionality.",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "duplicated_automation_workflow",
                    models.OneToOneField(
                        help_text="The duplicated automation workflow.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicated_from_jobs",
                        to="automation.automationworkflow",
                    ),
                ),
                (
                    "original_automation_workflow",
                    models.ForeignKey(
                        help_text="The automation workflow to duplicate.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicated_by_jobs",
                        to="automation.automationworkflow",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.job", models.Model),
        ),
    ]
