# Generated by Django 5.0.13 on 2025-04-28 10:15

import django.db.models.deletion
from django.db import migrations, models

import baserow.contrib.automation.nodes.models
import baserow.core.fields
import baserow.core.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0002_automationworkflow_duplicateautomationworkflowjob"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0098_alter_userfile_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationNode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                ("trashed", models.BooleanField(db_index=True, default=False)),
                (
                    "order",
                    models.DecimalField(
                        decimal_places=20,
                        default=1,
                        editable=False,
                        help_text="Lowest first.",
                        max_digits=40,
                    ),
                ),
                ("previous_node_output", models.CharField(default="")),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=models.SET(
                            baserow.contrib.automation.nodes.models.get_default_node_content_type
                        ),
                        related_name="automation_workflow_node_content_types",
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
                (
                    "parent_node",
                    models.ForeignKey(
                        blank=True,
                        help_text="The parent automation node.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_workflow_child_nodes",
                        to="automation.automationnode",
                    ),
                ),
                (
                    "previous_node",
                    models.ForeignKey(
                        blank=True,
                        help_text="The previous automation node.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_workflow_previous_nodes",
                        to="automation.automationnode",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_workflow_nodes",
                        to="automation.automationworkflow",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
            bases=(
                models.Model,
                baserow.core.mixins.FractionOrderableMixin,
                baserow.core.mixins.PolymorphicContentTypeMixin,
                baserow.core.mixins.WithRegistry,
            ),
        ),
        migrations.CreateModel(
            name="LocalBaserowCreateRowActionNode",
            fields=[
                (
                    "automationnode_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="automation.automationnode",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        help_text="The service which this action is associated with.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.service",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("automation.automationnode",),
        ),
        migrations.CreateModel(
            name="LocalBaserowRowCreatedTriggerNode",
            fields=[
                (
                    "automationnode_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="automation.automationnode",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        help_text="The service which this action is associated with.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.service",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("automation.automationnode",),
        ),
    ]
