# Generated by Django 5.0.13 on 2025-05-13 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0003_automationnode_localbaserowcreaterowactionnode_and_more"),
        ("core", "0099_mcpendpoint"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LocalBaserowCreateRowActionNode",
        ),
        migrations.DeleteModel(
            name="LocalBaserowRowCreatedTriggerNode",
        ),
        migrations.CreateModel(
            name="LocalBaserowCreateRowActionNode",
            fields=[
                (
                    "automationnode_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="automation.automationnode",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("automation.automationnode",),
        ),
        migrations.AddField(
            model_name="automationnode",
            name="service",
            field=models.OneToOneField(
                help_text="The service which this node is associated with.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="automation_workflow_node",
                to="core.service",
            ),
        ),
        migrations.CreateModel(
            name="LocalBaserowRowCreatedTriggerNode",
            fields=[
                (
                    "automationnode_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="automation.automationnode",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("automation.automationnode",),
        ),
        migrations.AddField(
            model_name="automationworkflow",
            name="published",
            field=models.BooleanField(
                default=False, help_text="Whether the workflow is published."
            ),
        ),
    ]
