# Generated by Django 5.0.13 on 2025-06-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0005_rows_updated_deleted_triggers"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationworkflow",
            name="allow_test_run_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
