# Generated by Django 5.0.13 on 2025-07-22 10:31

from django.db import migrations


def forward(apps, schema_editor):
    from loguru import logger

    AutomationNode = apps.get_model("automation", "AutomationNode")
    AutomationWorkflow = apps.get_model("automation", "AutomationWorkflow")

    automation_node_updates = []
    workflows = AutomationWorkflow.objects.all()
    for workflow in workflows:
        nodes = AutomationNode.objects.filter(workflow=workflow).order_by("order")
        for index, node in enumerate(nodes):
            if node.previous_node_id is None:
                node.previous_node_id = nodes[index - 1].id if index > 0 else None
                automation_node_updates.append(node)
            else:
                # If the previous_node_id is already set, we don't want to change it.
                # The migration is unexpectedly being run on an instance that has
                # already been migrated.
                logger.debug(
                    f"Skipping node {node.id} with previous_node_id "
                    f"{node.previous_node_id}, unexpected state found."
                )
                continue

    AutomationNode.objects.bulk_update(automation_node_updates, ["previous_node_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0012_get_list_aggregate_rows_nodes"),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]
