# Generated by Django 5.0.13 on 2025-07-25 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0013_apply_previous_node_ids"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationWorkflowHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_on", models.DateTimeField()),
                ("completed_on", models.DateTimeField(blank=True, null=True)),
                ("message", models.TextField()),
                ("is_test_run", models.BooleanField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("disabled", "Disabled"),
                            ("started", "Started"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_history",
                        to="automation.automationworkflow",
                    ),
                ),
            ],
            options={
                "ordering": ("-started_on",),
                "abstract": False,
            },
        ),
    ]
