# Generated by Django 5.0.13 on 2025-08-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0014_automationworkflowhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationnode",
            name="label",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="A label to use when displaying this node in a graph.",
                max_length=75,
            ),
        ),
    ]
