# Generated by Django 5.0.13 on 2025-08-28 10:06

from django.db import migrations, models

from baserow.contrib.automation.workflows.constants import WorkflowState


def forwards_fill_state(apps, schema_editor):
    AutomationWorkflow = apps.get_model("automation", "AutomationWorkflow")

    for workflow in AutomationWorkflow.objects.only(
        "id", "published", "paused", "disabled_on"
    ):
        new_state = WorkflowState.DRAFT
        if workflow.disabled_on:
            new_state = WorkflowState.DISABLED
        elif workflow.paused:
            new_state = WorkflowState.PAUSED
        elif workflow.published:
            new_state = WorkflowState.LIVE

        AutomationWorkflow.objects.filter(id=workflow.id).update(state=new_state)


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0016_corerouteractionnode"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationworkflow",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("live", "Live"),
                    ("paused", "Paused"),
                    ("disabled", "Disabled"),
                ],
                default="draft",
                db_default="draft",
                max_length=20,
                null=False,
            ),
        ),

        # Run a data migration to fill the state.
        migrations.RunPython(
            forwards_fill_state, reverse_code=migrations.RunPython.noop
        ),

        # Safely remove old fields.
        migrations.RemoveField(
            model_name="automationworkflow",
            name="disabled_on",
        ),
        migrations.RemoveField(
            model_name="automationworkflow",
            name="paused",
        ),
        migrations.RemoveField(
            model_name="automationworkflow",
            name="published",
        ),
    ]
