# Generated by Django 5.0.13 on 2025-09-05 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0017_remove_automationworkflow_disabled_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationworkflow",
            name="simulate_until_node",
            field=models.ForeignKey(
                blank=True,
                help_text="When set, upon the next workflow run, simulates the dispatch of the workflow until this node and updates the sample_data of the node's service.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="automation.automationnode",
            ),
        ),
    ]
