# Generated by Django 5.2.14 on 2026-06-25 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0035_coregotoactionnode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreResponseActionNode',
            fields=[
                ('automationnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='automation.automationnode')),
            ],
            options={
                'abstract': False,
            },
            bases=('automation.automationnode',),
        ),
        migrations.CreateModel(
            name='AutomationWorkflowHistoryResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.PositiveSmallIntegerField()),
                ('headers', models.JSONField(db_default={}, default=dict)),
                ('body', models.JSONField(blank=True, db_default=None, default=None, null=True)),
                ('body_type', models.CharField(max_length=10)),
                ('is_default', models.BooleanField(db_default=False, default=False)),
                ('source_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_history_responses', to='automation.automationnode')),
                ('workflow_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='automation.automationworkflowhistory')),
            ],
        ),
    ]
