# Generated by Django 5.2.16 on 2026-09-09 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0035_coregotoactionnode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='automationworkflowhistory',
            name='triggered_by',
            field=models.ForeignKey(blank=True, help_text='The user whose action started this run, when one is known. Set by a button field click; null for every other trigger.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
