receivers:
  otlp:
    protocols:
      grpc: # port 4317
      http: # port 4318

processors:
  # Disable sending spans for the sync templates task as it contains a huge number
  # which pointlessly uses up resource limits. Also disable silk spam.
  filter:
    traces:
      span:
        - 'IsMatch(name, ".*sync_templates_task.*") == true'
        - 'IsMatch(attributes["db.statement"], ".*silk.*") == true'
      spanevent:
        - 'IsMatch(name, ".*sync_templates_task.*") == true'
        - 'IsMatch(attributes["db.statement"], ".*silk.*") == true'
  batch:
    send_batch_size: 1000

exporters:
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${env:HONEYCOMB_API_KEY}"
  otlp/metrics:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${env:HONEYCOMB_API_KEY}"
      "x-honeycomb-dataset": "${env:HONEYCOMB_METRICS_DATASET}"
  logging:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp,logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/metrics,logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp,logging]

extensions:
  health_check: