from rest_framework.status import HTTP_400_BAD_REQUEST


ERROR_ALREADY_EXISTS = 'ERROR_EMAIL_ALREADY_EXISTS'
ERROR_USER_NOT_FOUND = 'ERROR_USER_NOT_FOUND'
ERROR_INVALID_OLD_PASSWORD = 'ERROR_INVALID_OLD_PASSWORD'
ERROR_HOSTNAME_IS_NOT_ALLOWED = (
    'ERROR_HOSTNAME_IS_NOT_ALLOWED',
    HTTP_400_BAD_REQUEST,
    'Only the hostname of the web frontend is allowed.'
)
