ERROR_ALREADY_EXISTS = "ERROR_EMAIL_ALREADY_EXISTS"
ERROR_USER_NOT_FOUND = "ERROR_USER_NOT_FOUND"
ERROR_INVALID_OLD_PASSWORD = "ERROR_INVALID_OLD_PASSWORD"
ERROR_DISABLED_SIGNUP = "ERROR_DISABLED_SIGNUP"
