from rest_framework.status import HTTP_404_NOT_FOUND, HTTP_405_METHOD_NOT_ALLOWED

ERROR_CORE_HTTP_TRIGGER_SERVICE_DOES_NOT_EXIST = (
    "ERROR_CORE_HTTP_TRIGGER_SERVICE_DOES_NOT_EXIST",
    HTTP_404_NOT_FOUND,
    "The requested HTTP trigger does not exist.",
)

ERROR_CORE_HTTP_TRIGGER_SERVICE_METHOD_NOT_ALLOWED = (
    "ERROR_CORE_HTTP_TRIGGER_SERVICE_METHOD_NOT_ALLOWED",
    HTTP_405_METHOD_NOT_ALLOWED,
    "The HTTP method is not allowed.",
)
