# Generated by Django 2.2.2 on 2019-09-13 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('application_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='core.Application')
                 ),
            ],
            bases=('core.application',),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')
                 ),
                ('order', models.PositiveIntegerField()),
                ('group', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='database.Database')
                 ),
            ],
        ),
    ]
