# Generated by Django 2.2.2 on 2019-12-20 12:50

import django.db.models.deletion
from django.db import migrations, models

import baserow.contrib.database.fields.models
import baserow.core.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("database", "0001_initial"),
    ]

    default_type = baserow.contrib.database.fields.models.get_default_field_content_type

    operations = [
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=models.SET(default_type),
                        related_name="database_fields",
                        to="contenttypes.ContentType",
                        verbose_name="content type",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="database.Table"
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
            bases=(
                baserow.core.mixins.OrderableMixin,
                baserow.core.mixins.PolymorphicContentTypeMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="BooleanField",
            fields=[
                (
                    "field_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="database.Field",
                    ),
                ),
            ],
            bases=("database.field",),
        ),
        migrations.CreateModel(
            name="NumberField",
            fields=[
                (
                    "field_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="database.Field",
                    ),
                ),
                (
                    "number_type",
                    models.CharField(
                        choices=[("INTEGER", "Integer"), ("DECIMAL", "Decimal")],
                        default="INTEGER",
                        max_length=32,
                    ),
                ),
                (
                    "number_decimal_places",
                    models.IntegerField(
                        choices=[
                            (1, "1.0"),
                            (2, "1.00"),
                            (3, "1.000"),
                            (4, "1.0000"),
                            (5, "1.00000"),
                        ],
                        default=1,
                    ),
                ),
                ("number_negative", models.BooleanField(default=False)),
            ],
            bases=("database.field",),
        ),
        migrations.CreateModel(
            name="TextField",
            fields=[
                (
                    "field_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="database.Field",
                    ),
                ),
                (
                    "text_default",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            bases=("database.field",),
        ),
    ]
