# Generated by Django 2.2.11 on 2020-08-19 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0008_auto_20200701_1608"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkRowField",
            fields=[
                (
                    "field_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="database.Field",
                    ),
                ),
                ("link_row_relation_id", models.IntegerField(blank=True, null=True)),
                (
                    "link_row_related_field",
                    models.ForeignKey(
                        blank=True,
                        help_text="The relation field in the other table.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="database.LinkRowField",
                    ),
                ),
                (
                    "link_row_table",
                    models.ForeignKey(
                        blank=True,
                        help_text="The table that the field has a relation with.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.Table",
                    ),
                ),
            ],
            bases=("database.field",),
        ),
    ]
