# Generated by Django 2.2.11 on 2021-03-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0026_auto_20210125_1454"),
    ]

    operations = [
        migrations.AddField(
            model_name="gridviewfieldoptions",
            name="order",
            field=models.SmallIntegerField(default=32767),
        ),
    ]
