# Generated by Django 2.2.11 on 2021-01-25 14:54

from django.db import migrations, connections
from django.conf import settings


def forward(apps, schema_editor):
    URLField = apps.get_model("database", "URLField")

    connection = connections[settings.USER_TABLE_DATABASE]
    with connection.schema_editor() as tables_schema_editor:
        # We need to stop the transaction because we might need to lock a lot of tables
        # which could result in an out of memory exception.
        tables_schema_editor.atomic.__exit__(None, None, None)

        for field in URLField.objects.all():
            table_name = f"database_table_{field.table.id}"
            field_name = f"field_{field.id}"
            tables_schema_editor.execute(
                f"""ALTER TABLE {table_name} ALTER COLUMN {field_name} TYPE text"""
            )


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0030_auto_20210526_1939"),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]
