# Generated by Django 2.2.24 on 2021-08-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0034_form_view"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="field",
            name="old_name",
        ),
    ]
