# Generated by Django 3.2.6 on 2021-08-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0036_createdonfield_lastmodifiedfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportjob",
            name="export_options",
            field=models.JSONField(),
        ),
    ]
