# Generated by Django 2.2.11 on 2021-06-14 09:08
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0041_add_generated_table_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="trashed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="table",
            name="trashed",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
