# Generated by Django 3.2.6 on 2021-12-21 13:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0053_add_and_move_public_flags"),
    ]

    operations = [
        migrations.CreateModel(
            name="RatingField",
            fields=[
                (
                    "field_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="database.field",
                    ),
                ),
                (
                    "max_value",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Maximum value the rating can take.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="dark-orange",
                        help_text="Color of the symbols.",
                        max_length=50,
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("star", "Star"),
                            ("heart", "Heart"),
                            ("thumbs-up", "Thumbs-up"),
                            ("flag", "Flags"),
                            ("smile", "Smile"),
                        ],
                        default="star",
                        help_text=(
                            "Rating style. Allowed values: star, heart, "
                            "thumbs-up, flag, smile."
                        ),
                        max_length=50,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("database.field",),
        ),
    ]
