# Generated by Django 3.2.6 on 2021-12-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0054_ratingfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="formview",
            name="submit_text",
            field=models.TextField(
                default="Submit", help_text="The text displayed on the submit button."
            ),
        ),
    ]
