# Generated by Django 3.2.6 on 2021-12-16 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0055_formview_submit_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryview",
            name="card_cover_image_field",
            field=models.ForeignKey(
                blank=True,
                help_text="References a file field of which the first image must be "
                "shown as card cover image.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gallery_view_card_cover_field",
                to="database.filefield",
            ),
        ),
    ]
