# Generated by Django 3.2.6 on 2021-11-01 09:38
from django.db import migrations

# noinspection PyPep8Naming


def reverse(apps, schema_editor):
    pass


# noinspection PyPep8Naming
def forward(apps, schema_editor):
    FormulaField = apps.get_model("database", "FormulaField")
    invalid_pks = FormulaField.objects.filter(
        formula_type__in=["invalid", "array", "single_select"]
    )
    ViewFilter = apps.get_model("database", "ViewFilter")
    ViewSort = apps.get_model("database", "ViewSort")
    invalid_filters, _ = ViewFilter.objects.filter(field__in=invalid_pks).delete()
    invalid_sorts, _ = ViewSort.objects.filter(field__in=invalid_pks).delete()
    print(f"Fixed {invalid_filters} invalid filters")
    print(f"Fixed {invalid_sorts} invalid sorts")


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0056_galleryview_card_cover_image_field"),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
