# Generated by Django 3.2.6 on 2021-12-21 13:15

from django.db import migrations


def reverse(apps, schema_editor):
    pass


# noinspection PyPep8Naming
def forward(apps, schema_editor):
    FormulaField = apps.get_model("database", "FormulaField")
    LookupField = apps.get_model("database", "LookupField")
    ContentType = apps.get_model("contenttypes", "ContentType")

    formula_field_content_type_id = ContentType.objects.get_for_model(FormulaField).id
    lookup_field_content_type_id = ContentType.objects.get_for_model(LookupField).id
    for f in FormulaField.objects.exclude(
        content_type_id__in=[
            formula_field_content_type_id,
            lookup_field_content_type_id,
        ]
    ):
        f.delete(keep_parents=True)


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0057_fix_invalid_type_filters_and_sorts"),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
