# Generated by Django 3.2.6 on 2022-02-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0063_drop_number_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="gridviewfieldoptions",
            name="aggregation_raw_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Indicates how to compute the raw aggregation value from database. "
                    "This type must be registered in the backend prior to use it."
                ),
                max_length=48,
            ),
        ),
        migrations.AddField(
            model_name="gridviewfieldoptions",
            name="aggregation_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Indicates how the field value is aggregated. This value is "
                    "different from the `aggregation_raw_type`. The "
                    "`aggregation_raw_type` is the value extracted from the database, "
                    "while the `aggregation_type` can implies further calculations. "
                    "For example: if you want to compute an average, `sum` is going to "
                    "be the `aggregation_raw_type`, the value extracted from "
                    "database, and `sum / row_count` will be the aggregation result "
                    "displayed to the user. This aggregation_type should be used by "
                    "the client to compute the final value."
                ),
                max_length=48,
            ),
        ),
    ]
