# Generated by Django 3.2.12 on 2022-03-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0067_viewdecoration"),
    ]

    operations = [
        migrations.AddField(
            model_name="view",
            name="public_view_password",
            field=models.CharField(
                blank=True,
                help_text="The password required to access the public view URL.",
                max_length=128,
            ),
        ),
    ]
