# Generated by Django 3.2.12 on 2022-04-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0068_view_public_view_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="view",
            name="trashed",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
