# Generated by Django 3.2.12 on 2022-04-20 21:27

import baserow.contrib.database.fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0070_trashedrows"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkrowfield",
            name="link_row_relation_id",
            field=baserow.contrib.database.fields.fields.SerialField(null=True),
        ),
    ]
