# Generated by Django 3.2.12 on 2022-05-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0071_alter_linkrowfield_link_row_relation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="gridview",
            name="row_identifier_type",
            field=models.CharField(
                choices=[("id", "Id"), ("count", "Count")], default="id", max_length=10
            ),
        ),
    ]
