# Generated by Django 3.2.13 on 2022-05-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0072_gridview_row_identifier_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulafield",
            name="number_decimal_places",
            field=models.IntegerField(
                choices=[
                    (0, "1"),
                    (1, "1.0"),
                    (2, "1.00"),
                    (3, "1.000"),
                    (4, "1.0000"),
                    (5, "1.00000"),
                    (6, "1.000000"),
                    (7, "1.0000000"),
                    (8, "1.00000000"),
                    (9, "1.000000000"),
                    (10, "1.0000000000"),
                ],
                default=None,
                help_text="The amount of digits allowed after the point.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="numberfield",
            name="number_decimal_places",
            field=models.IntegerField(
                choices=[
                    (0, "1"),
                    (1, "1.0"),
                    (2, "1.00"),
                    (3, "1.000"),
                    (4, "1.0000"),
                    (5, "1.00000"),
                    (6, "1.000000"),
                    (7, "1.0000000"),
                    (8, "1.00000000"),
                    (9, "1.000000000"),
                    (10, "1.0000000000"),
                ],
                default=0,
                help_text="The amount of digits allowed after the point.",
            ),
        ),
    ]
