# Generated by Django 3.2.13 on 2022-05-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0073_increase_available_number_dp"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="row_count",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="table",
            name="row_count_updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
