# Generated by Django 3.2.12 on 2022-05-24 12:55

import django.db.models.deletion
from django.db import migrations, models

import baserow.contrib.database.file_import.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_job"),
        ("database", "0075_change_export_cascade"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileImportJob",
            fields=[
                (
                    "job_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.job",
                    ),
                ),
                (
                    "data_file",
                    models.FileField(
                        null=True,
                        upload_to=baserow.contrib.database.file_import.models.file_import_directory_path,
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="database.table",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.job",),
        ),
    ]
