# Generated by Django 3.2.12 on 2022-05-24 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_job"),
        ("database", "0076_add_file_import_job"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AirtableImportJob",
        ),
        migrations.CreateModel(
            name="AirtableImportJob",
            fields=[
                (
                    "job_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.job",
                    ),
                ),
                (
                    "airtable_share_id",
                    models.CharField(
                        help_text="Public ID of the shared Airtable base that must "
                        "be imported.",
                        max_length=18,
                    ),
                ),
                ("timezone", models.CharField(max_length=255, null=True)),
                (
                    "database",
                    models.ForeignKey(
                        help_text="The imported Baserow database.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.application",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="The group where the Airtable base must be imported "
                        "into.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.group",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.job",),
        ),
    ]
