# Generated by Django 3.2.12 on 2022-05-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0077_recreate_airtable_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileimportjob",
            name="report",
            field=models.JSONField(default=dict),
        ),
    ]
