# Generated by Django 3.2.13 on 2022-06-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0078_fileimportjob_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="version",
            field=models.TextField(default="initial_version"),
        ),
    ]
