# Generated by Django 3.2.13 on 2022-07-04 11:24

import baserow.contrib.database.file_import.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0078_fileimportjob_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileimportjob",
            name="report",
            field=models.JSONField(
                default=baserow.contrib.database.file_import.models.report_default_value
            ),
        ),
        migrations.AlterField(
            model_name="fileimportjob",
            name="table",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="import_jobs",
                to="database.table",
            ),
        ),
    ]
