# Generated by Django 3.2.13 on 2022-08-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0085_alter_fileimportjob_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="formview",
            name="mode",
            field=models.TextField(
                choices=[("form", "form"), ("survey", "survey")],
                default="form",
                help_text="Configurable mode of the form.",
                max_length=64,
            ),
        ),
    ]
