# Generated by Django 3.2.13 on 2022-09-02 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_duplicateapplicationjob_user_action_group_id"),
        ("database", "0086_formview_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="duplicatetablejob",
            name="user_action_group_id",
            field=models.CharField(
                help_text="The user session uuid needed for undo/redo action group functionality.",
                max_length=36,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fileimportjob",
            name="user_action_group_id",
            field=models.CharField(
                help_text="The user session uuid needed for undo/redo action group functionality.",
                max_length=36,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="DuplicateFieldJob",
            fields=[
                (
                    "job_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.job",
                    ),
                ),
                (
                    "user_websocket_id",
                    models.CharField(
                        help_text="The user websocket uuid needed to manage signals sent correctly.",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "user_session_id",
                    models.CharField(
                        help_text="The user session uuid needed for undo/redo functionality.",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "user_action_group_id",
                    models.CharField(
                        help_text="The user session uuid needed for undo/redo action group functionality.",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "duplicate_data",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the data of the field should be duplicated.",
                    ),
                ),
                (
                    "duplicated_field",
                    models.OneToOneField(
                        help_text="The duplicated Baserow field.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicated_from_jobs",
                        to="database.field",
                    ),
                ),
                (
                    "original_field",
                    models.ForeignKey(
                        help_text="The Baserow field to duplicate.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicated_by_jobs",
                        to="database.field",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.job", models.Model),
        ),
    ]
