# Generated by Django 3.2.13 on 2022-09-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0089_update_webhook_url_validators"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulafield",
            name="array_formula_type",
            field=models.TextField(
                choices=[
                    ("invalid", "invalid"),
                    ("text", "text"),
                    ("char", "char"),
                    ("link", "link"),
                    ("date_interval", "date_interval"),
                    ("date", "date"),
                    ("boolean", "boolean"),
                    ("number", "number"),
                    ("single_select", "single_select"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="formulafield",
            name="formula_type",
            field=models.TextField(
                choices=[
                    ("invalid", "invalid"),
                    ("text", "text"),
                    ("char", "char"),
                    ("link", "link"),
                    ("date_interval", "date_interval"),
                    ("date", "date"),
                    ("boolean", "boolean"),
                    ("number", "number"),
                    ("array", "array"),
                    ("single_select", "single_select"),
                ],
                default="invalid",
            ),
        ),
    ]
