# Generated by Django 3.2.13 on 2022-09-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0090_add_link_formula_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="view",
            name="show_logo",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether the logo should be shown in the public view.",
            ),
        ),
    ]
