# Generated by Django 3.2.13 on 2022-11-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0091_view_show_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="name",
            field=models.CharField(
                help_text="The human readable name of the database token for the user.",
                max_length=100,
            ),
        ),
    ]
