# Generated by Django 3.2.13 on 2022-11-20 21:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0092_alter_token_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tablewebhookcall",
            old_name="id",
            new_name="event_id",
        ),
        migrations.AlterField(
            model_name="tablewebhookcall",
            name="event_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Event ID where the call originated from.",
            ),
        ),
        migrations.AddField(
            model_name="tablewebhookcall",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
            preserve_default=False,
        ),
    ]
