# Generated by Django 3.2.13 on 2023-01-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0095_update_exportjob_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="duplicatefieldjob",
            name="user_ip_address",
            field=models.CharField(
                help_text="The user IP address.", max_length=45, null=True
            ),
        ),
        migrations.AddField(
            model_name="duplicatetablejob",
            name="user_ip_address",
            field=models.CharField(
                help_text="The user IP address.", max_length=45, null=True
            ),
        ),
        migrations.AddField(
            model_name="fileimportjob",
            name="user_ip_address",
            field=models.CharField(
                help_text="The user IP address.", max_length=45, null=True
            ),
        ),
    ]
