# Generated by Django 3.2.13 on 2023-01-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0096_add_user_ip_address_to_jobs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="duplicatefieldjob",
            name="user_ip_address",
            field=models.GenericIPAddressField(
                help_text="The user IP address.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="duplicatetablejob",
            name="user_ip_address",
            field=models.GenericIPAddressField(
                help_text="The user IP address.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="fileimportjob",
            name="user_ip_address",
            field=models.GenericIPAddressField(
                help_text="The user IP address.", null=True
            ),
        ),
    ]
