# Generated by Django 3.2.13 on 2023-01-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0098_view_ownership_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="view",
            name="ownership_type",
            field=models.CharField(
                default="collaborative",
                help_text="Indicates how the access to the view is determined. "
                "By default, views are collaborative and shared for all users "
                "that have access to the table.",
                max_length=255,
            ),
        ),
    ]
