# Generated by Django 3.2.13 on 2023-01-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0099_alter_view_ownership_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="airtableimportjob",
            name="user_ip_address",
            field=models.GenericIPAddressField(
                help_text="The user IP address.", null=True
            ),
        ),
    ]
