# Generated by Django 3.2.13 on 2023-02-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0101_formulafield_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="createdonfield",
            name="date_force_timezone",
            field=models.CharField(
                help_text="Force a timezone for the field overriding user profile settings.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="createdonfield",
            name="date_show_tzinfo",
            field=models.BooleanField(
                default=False, help_text="Indicates if the timezone should be shown."
            ),
        ),
        migrations.AddField(
            model_name="datefield",
            name="date_force_timezone",
            field=models.CharField(
                help_text="Force a timezone for the field overriding user profile settings.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="datefield",
            name="date_show_tzinfo",
            field=models.BooleanField(
                default=False, help_text="Indicates if the timezone should be shown."
            ),
        ),
        migrations.AddField(
            model_name="formulafield",
            name="date_force_timezone",
            field=models.CharField(
                help_text="Force a timezone for the field overriding user profile settings.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="formulafield",
            name="date_show_tzinfo",
            field=models.BooleanField(
                default=None,
                help_text="Indicates if the time zone should be shown.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lastmodifiedfield",
            name="date_force_timezone",
            field=models.CharField(
                help_text="Force a timezone for the field overriding user profile settings.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lastmodifiedfield",
            name="date_show_tzinfo",
            field=models.BooleanField(
                default=False, help_text="Indicates if the timezone should be shown."
            ),
        ),
    ]
