# Generated by Django 3.2.13 on 2023-02-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0104_remove_timezone_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulafield",
            name="needs_periodic_update",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the field needs to be periodically updated.",
            ),
        ),
    ]
