# Generated by Django 3.2.18 on 2023-03-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0106_add_to_timestamptz_formula"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokenpermission",
            name="type",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("read", "Read"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                ],
                db_index=True,
                max_length=6,
            ),
        ),
    ]
