# Generated by Django 3.2.13 on 2023-01-16 16:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0108_rename_group_airtableimportjob_workspace"),
    ]

    operations = [
        migrations.RenameField(
            model_name="token",
            old_name="group",
            new_name="workspace",
        ),
    ]
