# Generated by Django 3.2.13 on 2023-05-08 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0112_view_db_index_name"),
    ]

    operations = [
        migrations.RunSQL(
            (
                """
create or replace function try_datetime_format_tz(
    p_in timestamptz,
    p_format text,
    p_timezone text
)
    returns text
as
$$
begin
    return to_char(p_in at time zone p_timezone, p_format);
exception when others then
    return null;
end;
$$
    language plpgsql;
"""
            ),
            (
                "DROP FUNCTION IF EXISTS try_datetime_format_tz(timestamptz, text, text);"
            ),
        )
    ]
