# Generated by Django 3.2.18 on 2023-05-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0113_add_datetime_format_tz_formula"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airtableimportjob",
            name="airtable_share_id",
            field=models.CharField(
                help_text="Public ID of the shared Airtable base that must be imported.",
                max_length=200,
            ),
        ),
    ]
