# Generated by Django 3.2.18 on 2023-05-25 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0114_alter_airtableimportjob_airtable_share_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountField",
            fields=[
                (
                    "formulafield_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="database.formulafield",
                    ),
                ),
                (
                    "through_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="count_fields_used_by",
                        to="database.field",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("database.formulafield",),
        ),
    ]
