# Generated by Django 3.2.18 on 2023-06-07 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0115_countfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="RollupField",
            fields=[
                (
                    "formulafield_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="database.formulafield",
                    ),
                ),
                (
                    "rollup_function",
                    models.CharField(
                        blank=True,
                        help_text="The rollup formula function that must be applied.",
                        max_length=64,
                    ),
                ),
                (
                    "target_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="targeting_rollup_fields",
                        to="database.field",
                    ),
                ),
                (
                    "through_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rollup_fields_used_by",
                        to="database.field",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("database.formulafield",),
        ),
    ]
