# Generated by Django 3.2.18 on 2023-06-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0117_synced_datetime_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="needs_background_update_column_added",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the table has had the "
                "background_update_needed column added.",
            ),
        ),
    ]
