# Generated by Django 3.2.18 on 2023-06-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0118_table_needs_background_update_column_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="tsvector_column_created",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether a `tsvector` has been created for this "
                "field yet. This value will be False for fields created "
                "before the full text search release which haven't been "
                "lazily migrated yet. Or for users who have turned off full "
                "text search entirely.",
            ),
        ),
    ]
