# Generated by Django 3.2.18 on 2023-07-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0120_tsvector_updater"),
    ]

    operations = [
        migrations.AddField(
            model_name="multiplecollaboratorsfield",
            name="notify_user_when_added",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the user should be notified when they are added as a collaborator.",
            ),
            preserve_default=False,
        ),
    ]
