# Generated by Django 3.2.18 on 2023-07-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0121_multiplecollaboratorsfield_notify_user_when_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multiplecollaboratorsfield",
            name="notify_user_when_added",
            field=models.BooleanField(
                default=True,
                help_text="Indicates if the user should be notified when they are added as a collaborator.",
            ),
        ),
    ]
