# Generated by Django 3.2.20 on 2023-08-29 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0125_add_row_history"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rowhistory",
            options={"ordering": ("-action_timestamp", "-id")},
        ),
    ]
