# Generated by Django 3.2.21 on 2023-10-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0130_add_single_file_formula_type"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="rowhistory",
            name="database_ro_table_i_7d9a59_idx",
        ),
        migrations.AddIndex(
            model_name="rowhistory",
            index=models.Index(
                fields=["table", "row_id", "-action_timestamp", "-id"],
                name="database_ro_table_i_5044cd_idx",
            ),
        ),
    ]
