# Generated by Django 3.2.21 on 2023-10-12 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0131_auto_20231017_0754"),
    ]

    operations = [
        migrations.CreateModel(
            name="ViewFilterGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filter_type",
                    models.CharField(
                        choices=[("AND", "And"), ("OR", "Or")],
                        default="AND",
                        help_text="Indicates whether all the rows should apply to all filters (AND) or to any filter (OR) in the group to be shown.",
                        max_length=3,
                    ),
                ),
                (
                    "parent_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.viewfiltergroup",
                    ),
                ),
                (
                    "view",
                    models.ForeignKey(
                        help_text="The view to which the filter group applies to. Each view can have its own filter groups.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filter_groups",
                        to="database.view",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="FormViewFieldOptionsConditionGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filter_type",
                    models.CharField(
                        choices=[("AND", "And"), ("OR", "Or")],
                        default="AND",
                        help_text="Indicates whether all the rows should apply to all filters (AND) or to any filter (OR) in the group to be shown.",
                        max_length=3,
                    ),
                ),
                (
                    "field_option",
                    models.ForeignKey(
                        help_text="The form view option where the condition is related to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="condition_groups",
                        to="database.formviewfieldoptions",
                    ),
                ),
                (
                    "parent_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.formviewfieldoptionsconditiongroup",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.AddField(
            model_name="formviewfieldoptionscondition",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conditions",
                to="database.formviewfieldoptionsconditiongroup",
            ),
        ),
        migrations.AddField(
            model_name="viewfilter",
            name="group",
            field=models.ForeignKey(
                help_text="The filter group to which the filter applies. Each view can have his own filters.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filters",
                to="database.viewfiltergroup",
            ),
        ),
    ]
