# Generated by Django 3.2.21 on 2023-10-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0132_add_filter_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="formviewfieldoptions",
            name="field_component",
            field=models.CharField(
                default="default",
                help_text="Indicates which field input component is used in the form. The value is only used in the frontend, and can differ per field.",
                max_length=32,
            ),
        ),
    ]
