# Generated by Django 3.2.21 on 2023-11-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0135_uuidfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="last_modified_by_column_added",
            preserve_default=False,
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the table has had the last_modified_by column added.",
                null=True,
            ),
        ),
    ]
