# Generated by Django 3.2.21 on 2023-11-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0136_table_last_modified_by_column_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="last_modified_by_column_added",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether the table has had the last_modified_by column added.",
                null=True,
            ),
        ),
    ]
