# Generated by Django 3.2.21 on 2023-12-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0143_add_table_created_by_column_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="created_by_column_added",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether the table has had the created_by column added.",
                null=True,
            ),
        ),
    ]
