# Generated by Django 3.2.21 on 2023-11-16 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0145_autonumberfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="DurationField",
            fields=[
                (
                    "field_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="database.field",
                    ),
                ),
                (
                    "duration_format",
                    models.CharField(
                        choices=[
                            ("h:mm", "hours:minutes"),
                            ("h:mm:ss", "hours:minutes:seconds"),
                            ("h:mm:ss.s", "hours:minutes:seconds:deciseconds"),
                            ("h:mm:ss.ss", "hours:minutes:seconds:centiseconds"),
                            ("h:mm:ss.sss", "hours:minutes:seconds:milliseconds"),
                        ],
                        default="h:mm",
                        help_text="The format of the duration.",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("database.field",),
        ),
    ]
