# Generated by Django 3.2.21 on 2023-12-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0146_durationfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="viewgroupby",
            name="width",
            field=models.PositiveIntegerField(
                default=200,
                help_text="The pixel width of the group by in the related view.",
            ),
        ),
    ]
