# Generated by Django 4.0.10 on 2024-01-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0149_alter_durationfield_duration_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulafield",
            name="duration_format",
            field=models.CharField(
                choices=[
                    ("h:mm", "hours:minutes"),
                    ("h:mm:ss", "hours:minutes:seconds"),
                    ("h:mm:ss.s", "hours:minutes:seconds:deciseconds"),
                    ("h:mm:ss.ss", "hours:minutes:seconds:centiseconds"),
                    ("h:mm:ss.sss", "hours:minutes:seconds:milliseconds"),
                    ("d h", "days:hours"),
                    ("d h:mm", "days:hours:minutes"),
                    ("d h:mm:ss", "days:hours:minutes:seconds"),
                ],
                default="h:mm",
                help_text="The format of the duration.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="formulafield",
            name="array_formula_type",
            field=models.TextField(
                choices=[
                    ("invalid", "invalid"),
                    ("text", "text"),
                    ("char", "char"),
                    ("button", "button"),
                    ("link", "link"),
                    ("date_interval", "date_interval"),
                    ("duration", "duration"),
                    ("date", "date"),
                    ("boolean", "boolean"),
                    ("number", "number"),
                    ("single_select", "single_select"),
                    ("multiple_select", "multiple_select"),
                    ("single_file", "single_file"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="formulafield",
            name="formula_type",
            field=models.TextField(
                choices=[
                    ("invalid", "invalid"),
                    ("text", "text"),
                    ("char", "char"),
                    ("button", "button"),
                    ("link", "link"),
                    ("date_interval", "date_interval"),
                    ("duration", "duration"),
                    ("date", "date"),
                    ("boolean", "boolean"),
                    ("number", "number"),
                    ("array", "array"),
                    ("single_select", "single_select"),
                    ("multiple_select", "multiple_select"),
                    ("single_file", "single_file"),
                ],
                default="invalid",
            ),
        ),
    ]
