# Generated by Django 4.1.13 on 2024-02-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0151_tableusageupdate_tableusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="longtextfield",
            name="long_text_enable_rich_text",
            field=models.BooleanField(
                default=False,
                help_text="Enable rich text formatting for the field.",
                null=True,
            ),
        ),
    ]
