# Generated by Django 4.1.13 on 2024-03-20 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0153_passwordfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="RichTextFieldMention",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row_id",
                    models.PositiveIntegerField(
                        help_text="The row id that the user mention is in."
                    ),
                ),
                (
                    "marked_for_deletion_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="The date and time that the mention has been marked as ready for deletion.",
                        null=True,
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        help_text="The field that the user mention is in.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="database.field",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        help_text="The table that the user mention is in.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="database.table",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user that is mentioned.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="richtextfieldmention",
            index=models.Index(
                fields=["row_id", "field"], name="database_ri_row_id_40f362_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="richtextfieldmention",
            unique_together={("table", "row_id", "field", "user")},
        ),
    ]
