# Generated by Django 4.1.13 on 2024-04-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0154_richtextfieldmention_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="durationfield",
            name="duration_format",
            field=models.CharField(
                choices=[
                    ("h:mm", "hours:minutes"),
                    ("h:mm:ss", "hours:minutes:seconds"),
                    ("h:mm:ss.s", "hours:minutes:seconds:deciseconds"),
                    ("h:mm:ss.ss", "hours:minutes:seconds:centiseconds"),
                    ("h:mm:ss.sss", "hours:minutes:seconds:milliseconds"),
                    ("d h", "days:hours"),
                    ("d h:mm", "days:hours:minutes"),
                    ("d h:mm:ss", "days:hours:minutes:seconds"),
                    ("d h mm", "days:hours:minutes:with_spaces"),
                    ("d h mm ss", "days:hours:minutes:seconds:with_spaces"),
                ],
                default="h:mm",
                help_text="The format of the duration.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="formulafield",
            name="duration_format",
            field=models.CharField(
                choices=[
                    ("h:mm", "hours:minutes"),
                    ("h:mm:ss", "hours:minutes:seconds"),
                    ("h:mm:ss.s", "hours:minutes:seconds:deciseconds"),
                    ("h:mm:ss.ss", "hours:minutes:seconds:centiseconds"),
                    ("h:mm:ss.sss", "hours:minutes:seconds:milliseconds"),
                    ("d h", "days:hours"),
                    ("d h:mm", "days:hours:minutes"),
                    ("d h:mm:ss", "days:hours:minutes:seconds"),
                    ("d h mm", "days:hours:minutes:with_spaces"),
                    ("d h mm ss", "days:hours:minutes:seconds:with_spaces"),
                ],
                default="h:mm",
                help_text="The format of the duration.",
                max_length=32,
                null=True,
            ),
        ),
    ]
