# Generated by Django 4.1.13 on 2024-05-22 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0156_interval_to_text_to_interval_db_functions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airtableimportjob",
            name="database",
            field=models.ForeignKey(
                help_text="The imported Baserow database.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="database.database",
            ),
        ),
    ]
