# Generated by Django 4.1.13 on 2024-05-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('database', '0157_alter_airtableimportjob_database')
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="description",
            field=models.TextField(
                default=None, help_text="Field description", null=True
            ),
        ),
    ]
