# Generated by Django 4.2.13 on 2024-07-06 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0158_field_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkrowfield",
            name="link_row_limit_selection_view",
            field=models.ForeignKey(
                blank=True,
                help_text="Visually only select rows that match the view filter. Note "
                          "that this is frontend only, and it will still be possible "
                          "to make relationship to rows that don't match the view.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="database.view",
            ),
        ),
    ]
