# Generated by Django 4.2.13 on 2024-07-15 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0159_alter_formulafield_array_formula_type_and_more"),
        ("database", "0159_linkrowfield_link_row_limit_selection_view"),
    ]

    operations = []
