# Generated by Django 4.1.13 on 2024-05-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0161_tourl_function"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulafield",
            name="expand_formula_when_referenced",
            field=models.BooleanField(
                default=True,
                null=True,
                help_text=(
                    "Indicates if the formula should be expanded when referenced (i.e. contains a lookup)  or if it's possible to use the calculated value directly.",
                ),
            ),
            preserve_default=False,
        ),
    ]
