# Generated by Django 4.1.13 on 2024-05-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0162_formulafield_expand_formula_when_referenced"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulafield",
            name="expand_formula_when_referenced",
            field=models.BooleanField(
                default=False,
                null=True,
                help_text=(
                    "Indicates if the formula should be expanded when referenced (i.e. contains a lookup) or if it's possible to use the calculated value directly.",
                ),
            ),
        ),
    ]
