# Generated by Django 4.2.13 on 2024-09-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0163_alter_formulafield_expand_formula_when_referenced"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="immutable_properties",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the field properties are immutable. If true, then it won't be possible to change the properties and the type via the API.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="field",
            name="immutable_type",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the field type is immutable. If true, then it won't be possible to change the field type via the API.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="field",
            name="read_only",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the field is read-only regardless of the field type. If true, then it won't be possible to update the cell value via the API.",
                null=True,
            ),
        ),
    ]
