# Generated by Django 5.0.9 on 2024-09-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0165_datasync_icalcalendardatasync_syncdatasynctablejob_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gridview",
            name="row_height_size",
            field=models.CharField(
                choices=[("small", "Small"), ("medium", "Medium"), ("large", "Large")],
                db_default="small",
                default="small",
                max_length=10,
            ),
        ),
    ]
