# Generated by Django 4.2.13 on 2024-09-15 17:00

from django.db import migrations, transaction


def forward(apps, schema_editor):
    """
    This migration will create individual TableWebhookEvent entries
    for all deprecated single row webhooks that has include_all_events
    set to True.
    """

    TableWebhookEvent = apps.get_model("database", "TableWebhookEvent")

    with transaction.atomic():
        TableWebhookEvent.objects.filter(event_type="row.created").update(event_type="rows.created")
        TableWebhookEvent.objects.filter(event_type="row.updated").update(event_type="rows.updated")
        TableWebhookEvent.objects.filter(event_type="row.deleted").update(event_type="rows.deleted")


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0166_gridview_row_height_size"),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]
