# Generated by Django 4.2.13 on 2024-09-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0167_remove_singular_webhook_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="tablewebhookevent",
            name="fields",
            field=models.ManyToManyField(to="database.field"),
        ),
    ]
