# Generated by Django 5.0.9 on 2024-10-02 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0168_tablewebhookevent_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryview",
            name="card_cover_image_field",
            field=models.ForeignKey(
                blank=True,
                help_text="References a file field of which the first image must be shown as card cover image.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gallery_view_card_cover_field",
                to="database.field",
            ),
        ),
    ]
