# Generated by Django 5.0.9 on 2024-10-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0170_update_password_tsv_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formview",
            name="submit_action_redirect_url",
            field=models.URLField(
                blank=True,
                help_text="If the `submit_action` is REDIRECT,then the visitors will be redirected to the this URL after submitting the form.",
                max_length=2000,
            ),
        ),
    ]
