# Generated by Django 5.0.9 on 2024-11-06 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0171_alter_formview_submit_action_redirect_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostgreSQLDataSync",
            fields=[
                (
                    "datasync_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="database.datasync",
                    ),
                ),
                ("postgresql_host", models.CharField(max_length=255)),
                ("postgresql_username", models.CharField(max_length=255)),
                ("postgresql_password", models.CharField(max_length=255)),
                ("postgresql_port", models.PositiveSmallIntegerField(default=5432)),
                ("postgresql_database", models.CharField(max_length=255)),
                (
                    "postgresql_schema",
                    models.CharField(default="public", max_length=255),
                ),
                ("postgresql_table", models.CharField(max_length=255)),
                (
                    "postgresql_sslmode",
                    models.CharField(
                        choices=[
                            ("disable", "disable"),
                            ("allow", "allow"),
                            ("prefer", "prefer"),
                            ("require", "require"),
                            ("verify-ca", "verify-ca"),
                            ("verify-full", "verify-full"),
                        ],
                        default="prefer",
                        max_length=12,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("database.datasync",),
        ),
    ]
