# Generated by Django 5.0.9 on 2024-11-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0172_postgresqldatasync"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasyncsyncedproperty",
            name="metadata",
            field=models.JSONField(
                default=None,
                help_text="Private metadata needed to help keep the data in sync.",
                null=True,
            ),
        ),
    ]
