# Generated by Django 5.0.9 on 2024-12-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0173_datasyncsyncedproperty_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulafield",
            name="number_prefix",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="The prefix to use for the field.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="formulafield",
            name="number_separator",
            field=models.CharField(
                choices=[
                    ("", "No formatting"),
                    ("SPACE_COMMA", "Space, comma"),
                    ("SPACE_PERIOD", "Space, period"),
                    ("COMMA_PERIOD", "Comma, period"),
                    ("PERIOD_COMMA", "Period, comma"),
                ],
                db_default="",
                default="",
                help_text="The thousand and decimal separator to use for the field.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="formulafield",
            name="number_suffix",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="The suffix to use for the field.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="numberfield",
            name="number_prefix",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="The prefix to use for the field.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="numberfield",
            name="number_separator",
            field=models.CharField(
                choices=[
                    ("", "No formatting"),
                    ("SPACE_COMMA", "Space, comma"),
                    ("SPACE_PERIOD", "Space, period"),
                    ("COMMA_PERIOD", "Comma, period"),
                    ("PERIOD_COMMA", "Period, comma"),
                ],
                db_default="",
                default="",
                help_text="The thousand and decimal separator to use for the field.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="numberfield",
            name="number_suffix",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="The suffix to use for the field.",
                max_length=100,
            ),
        ),
    ]
