# Generated by Django 5.0.9 on 2024-12-03 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0174_formulafield_number_prefix_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formviewfieldoptions",
            name="include_all_select_options",
            field=models.BooleanField(
                db_default=True,
                default=True,
                help_text="Indicates whether all fields must be included. Only works if the related field type can have select options.",
            ),
        ),
        migrations.CreateModel(
            name="FormViewFieldOptionsAllowedSelectOptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_view_field_options",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="database.formviewfieldoptions",
                    ),
                ),
                (
                    "select_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="database.selectoption",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="formviewfieldoptions",
            name="allowed_select_options",
            field=models.ManyToManyField(
                help_text="If `include_all_select_options` is True, then only these select options can be chosen.",
                through="database.FormViewFieldOptionsAllowedSelectOptions",
                to="database.selectoption",
            ),
        ),
    ]
