# Generated by Django 3.2.6 on 2021-09-15 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0175_formviewfieldoptions_include_all_select_options_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            (
                """
CREATE OR REPLACE FUNCTION try_regexp_replace(
    input_string TEXT,
    pattern TEXT,
    replacement TEXT,
    flags TEXT DEFAULT 'g',
    error_value TEXT DEFAULT ''
) RETURNS TEXT AS $$
DECLARE
    result TEXT;
BEGIN
    result := regexp_replace(input_string, pattern, replacement, flags);
    RETURN result;

EXCEPTION
    WHEN others THEN
        RETURN error_value;
END;
$$ LANGUAGE plpgsql;
"""
            ),
            ("DROP FUNCTION IF EXISTS try_regexp_replace(text, text, text, text, text);"),
        ),
    ]
