# Generated by Django 5.0.9 on 2025-01-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0178_remove_singleselect_missing_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulafield",
            name="array_formula_type",
            field=models.TextField(
                choices=[
                    ("invalid", "invalid"),
                    ("text", "text"),
                    ("char", "char"),
                    ("button", "button"),
                    ("link", "link"),
                    ("date_interval", "date_interval"),
                    ("duration", "duration"),
                    ("date", "date"),
                    ("boolean", "boolean"),
                    ("number", "number"),
                    ("single_select", "single_select"),
                    ("multiple_select", "multiple_select"),
                    ("single_file", "single_file"),
                    ("url", "url"),
                    ("multiple_collaborators", "multiple_collaborators"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="formulafield",
            name="formula_type",
            field=models.TextField(
                choices=[
                    ("invalid", "invalid"),
                    ("text", "text"),
                    ("char", "char"),
                    ("button", "button"),
                    ("link", "link"),
                    ("date_interval", "date_interval"),
                    ("duration", "duration"),
                    ("date", "date"),
                    ("boolean", "boolean"),
                    ("number", "number"),
                    ("array", "array"),
                    ("single_select", "single_select"),
                    ("multiple_select", "multiple_select"),
                    ("single_file", "single_file"),
                    ("url", "url"),
                    ("multiple_collaborators", "multiple_collaborators"),
                ],
                default="invalid",
            ),
        ),
    ]
