# Generated by Django 5.0.9 on 2024-12-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0179_alter_formulafield_array_formula_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="view",
            name="allow_public_export",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Indicates whether it's allowed to export a publicly shared view.",
            ),
        ),
    ]
