# Generated by Django 5.0.9 on 2025-03-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0180_view_allow_public_export"),
    ]

    operations = [
        migrations.AddField(
            model_name="tablewebhookcall",
            name="batch_id",
            field=models.PositiveIntegerField(
                help_text="The batch ID for this call. Null if not part of a batch. Used for batching multiple calls of the same event_id due to large data.",
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tablewebhookcall",
            unique_together={("event_id", "batch_id", "webhook", "event_type")},
        ),
    ]
