# Generated by Django 5.0.9 on 2025-03-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0182_tablewebhookevent_views_viewrows_viewsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="viewgroupby",
            name="type",
            field=models.CharField(
                db_default="default",
                default="default",
                help_text="Indicates the sort type. Will automatically fall back to `default` if incompatible with field type.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="viewsort",
            name="type",
            field=models.CharField(
                db_default="default",
                default="default",
                help_text="Indicates the sort type. Will automatically fall back to `default` if incompatible with field type.",
                max_length=32,
            ),
        ),
    ]
