# Generated by Django 5.0.13 on 2025-03-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0184_airtableimportjob_session_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ratingfield",
            name="style",
            field=models.CharField(
                choices=[
                    ("star", "Star"),
                    ("heart", "Heart"),
                    ("thumbs-up", "Thumbs Up"),
                    ("flag", "Flag"),
                    ("smile", "Smile"),
                ],
                default="star",
                help_text="Rating style. Allowed values: "
                "star, heart, thumbs-up, flag, smile.",
                max_length=50,
            ),
        ),
    ]
