# Generated by Django 5.0.13 on 2025-04-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0187_booleanfield_boolean_default_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkrowfield",
            name="link_row_multiple_relationships",
            field=models.BooleanField(
                db_default=True,
                default=True,
                help_text="Indicates whether it's allowed set multiple relationships per row. If disabled, it doesn't guarantee single relationships because they could have already existed or created through reversed relationship.",
            ),
        ),
    ]
