# Generated by Django 5.0.13 on 2025-06-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0190_datasync_auto_add_new_properties"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="db_index",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="If true, then an index will be added to the Baserow field to increase lookup and filter speed. Note that this comes at a performance cost when creating the row and updating the cell.",
            ),
        ),
    ]
