# Generated by Django 5.0.13 on 2025-07-04 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0191_field_db_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="search_data_initialized_at",
            field=models.DateTimeField(
                help_text="The timestamp when this field's tsvector values were first generated and added to the workspace search table. If null, the search data has not yet been initialized.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="immutable_properties",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the field properties are immutable. If true, then it won't be possible to change the properties and the type via the API.",
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="immutable_type",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the field type is immutable. If true, then it won't be possible to change the field type via the API.",
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="read_only",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the field is read-only regardless of the field type. If true, then it won't be possible to update the cell value via the API.",
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="tsvector_column_created",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether a `tsvector` has been created for this field yet. This value will be False for fields created before the full text search release which haven't been lazily migrated yet. Or for users who have turned off full text search entirely. DEPRECATED: remove in a future version and drop tsv_column in database table",
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="needs_background_update_column_added",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the table has had the background_update_needed column added. (DEPRECATED: remove in a future version)",
            ),
        ),
        migrations.CreateModel(
            name="PendingSearchValueUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row_id",
                    models.IntegerField(
                        help_text="The ID of the row to update. If null, all table rows will be updated.",
                        null=True,
                    ),
                ),
                (
                    "field_id",
                    models.IntegerField(help_text="The ID of the field to update."),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="database.table",
                    ),
                ),
            ],
            options={
                "ordering": ["field_id", "row_id"],
                "unique_together": {("field_id", "row_id")},
            },
        ),
    ]
