# Generated by Django 5.0.13 on 2025-06-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0193_fieldconstraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordfield",
            name="allow_endpoint_authentication",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="If true, then it's possible to use the `password_field_authentication` API endpoint to check if the password is correct. This can be used to use Baserow as authentication backend.",
            ),
        ),
    ]
