# Generated by Django 5.0.13 on 2025-07-22 10:17

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0194_passwordfield_allow_endpoint_authentication"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pendingsearchvalueupdate",
            options={},
        ),
        migrations.AddField(
            model_name="pendingsearchvalueupdate",
            name="deletion_workspace_id",
            field=models.IntegerField(
                help_text="The workspace ID used to mark this pending update for deletion once its associated table, field or row is permanently removed.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pendingsearchvalueupdate",
            name="updated_on",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                help_text="The time this update was last modified.",
            ),
        ),
        migrations.AlterField(
            model_name="pendingsearchvalueupdate",
            name="table",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="database.table",
            ),
        ),
        migrations.AddIndex(
            model_name="pendingsearchvalueupdate",
            index=models.Index(
                condition=models.Q(("deletion_workspace_id__isnull", False)),
                fields=["deletion_workspace_id", "field_id", "row_id"],
                name="pendingsearchvaluedeletion_idx",
            ),
        ),
    ]
