# Generated by Django 5.0.13 on 2025-07-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0195_alter_pendingsearchvalueupdate_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasync",
            name="two_way_sync",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="If enabled, then it's possible to make changes to the synced table. They will automatically be synced with the source data. Note that this is only possible if the data sync type has a two-way sync strategy.",
            ),
        ),
        migrations.AddField(
            model_name="datasync",
            name="two_way_sync_consecutive_failures",
            field=models.PositiveSmallIntegerField(
                db_default=0,
                default=0,
                help_text="Indicates the total number of two-way sync consecutive failures. Canbe used by the strategy to disable the two-way sync if needed.",
            ),
        ),
    ]
