# Generated by Django 5.0.13 on 2025-09-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0196_datasync_two_way_sync"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pendingsearchvalueupdate",
            index=models.Index(
                fields=["-updated_on"], name="pendingsearchvaluedeletion_ord"
            ),
        ),
    ]
