# Generated by Django 5.0.13 on 2025-09-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0197_pendingsearchvalueupdate_pendingsearchvaluedeletion_ord"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pendingsearchvalueupdate",
            index=models.Index(
                fields=["field_id", "-updated_on"],
                name="pendingsearchvaluedeletion_frd",
            ),
        ),
    ]
