# Generated by Django 5.2.16 on 2026-09-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0217_remove_buttonfield_url_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseworkflowaction',
            name='trashed',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
    ]
