TEAMS = "teams"
RBAC = "rbac"
SSO = "sso"
SUPPORT = "support"
AUDIT_LOG = "audit_log"
METRICS = "metrics"
SECURE_FILE_SERVE = "secure_file_serve"
ENTERPRISE_SETTINGS = "ENTERPRISE_SETTINGS"
DATA_SYNC = "data_sync"
ADVANCED_WEBHOOKS = "advanced_webhooks"
FIELD_LEVEL_PERMISSIONS = "field_level_permissions"

BUILDER_SSO = "application_user_sso"
BUILDER_NO_BRANDING = "application_no_branding"
BUILDER_FILE_INPUT = "builder_file_input"
BUILDER_CUSTOM_CODE = "builder_custom_code"
