# Generated by Django 5.0.9 on 2024-10-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="description",
            field=models.TextField(blank=True, db_default=""),
        ),
    ]
