# Generated by Django 5.0.9 on 2024-12-11 16:13

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models

import baserow.core.fields
import baserow.core.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0092_alter_userprofile_language"),
        ("dashboard", "0002_dashboard_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Widget",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                ("trashed", models.BooleanField(db_index=True, default=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "order",
                    models.DecimalField(
                        decimal_places=20,
                        default=Decimal("1"),
                        editable=False,
                        help_text="Lowest first.",
                        max_digits=40,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_widgets",
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.dashboard",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
            bases=(
                baserow.core.mixins.FractionOrderableMixin,
                baserow.core.mixins.PolymorphicContentTypeMixin,
                baserow.core.mixins.WithRegistry,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="DashboardDataSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trashed", models.BooleanField(db_index=True, default=False)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human name for this data source.",
                        max_length=255,
                    ),
                ),
                (
                    "order",
                    models.DecimalField(
                        decimal_places=20,
                        default=Decimal("1"),
                        editable=False,
                        help_text="Lowest first.",
                        max_digits=40,
                    ),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        help_text="Dashboard this data source is linked to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.dashboard",
                    ),
                ),
                (
                    "service",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dashboard_data_source",
                        to="core.service",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "unique_together": {("dashboard", "name")},
            },
            bases=(baserow.core.mixins.FractionOrderableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SummaryWidget",
            fields=[
                (
                    "widget_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dashboard.widget",
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        help_text="Data source for fetching the result to display.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dashboard.dashboarddatasource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("dashboard.widget",),
        ),
    ]
