# Generated by Django 3.2.6 on 2021-10-27 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0040_formulafield_remove_field_by_id"),
        ("baserow_premium", "0002_licenses"),
    ]

    operations = [
        migrations.CreateModel(
            name="KanbanView",
            fields=[
                (
                    "view_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="database.view",
                    ),
                ),
            ],
            options={
                "db_table": "database_kanbanview",
            },
            bases=("database.view",),
        ),
        migrations.CreateModel(
            name="KanbanViewFieldOptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hidden",
                    models.BooleanField(
                        default=True,
                        help_text="Whether or not the field should be hidden in the "
                        "card.",
                    ),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        default=32767,
                        help_text="The order that the field has in the form. Lower "
                        "value is first.",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="database.field"
                    ),
                ),
                (
                    "kanban_view",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="baserow_premium.kanbanview",
                    ),
                ),
            ],
            options={
                "db_table": "database_kanbanviewfieldoptions",
                "ordering": ("order", "field_id"),
            },
        ),
        migrations.AddField(
            model_name="kanbanview",
            name="field_options",
            field=models.ManyToManyField(
                through="baserow_premium.KanbanViewFieldOptions", to="database.Field"
            ),
        ),
        migrations.AddField(
            model_name="kanbanview",
            name="single_select_field",
            field=models.ForeignKey(
                blank=True,
                help_text="The single select field related to the options where rows "
                "should be stacked by.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kanban_view_single_select_field",
                to="database.singleselectfield",
            ),
        ),
    ]
