# Generated by Django 3.2.13 on 2022-10-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_premium", "0005_alter_rowcomment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="license",
            name="cached_untrusted_instance_wide",
            field=models.BooleanField(default=False),
        ),
    ]
