# Generated by Django 3.2.18 on 2023-06-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_premium", "0009_synced_datetime_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="rowcomment",
            name="trashed",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
