# Generated by Django 3.2.18 on 2023-06-26 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("baserow_premium", "0010_rowcomment_trashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="rowcomment",
            name="mentions",
            field=models.ManyToManyField(
                related_name="row_comment_mentions", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="rowcomment",
            name="message",
            field=models.JSONField(
                default=dict, help_text="The rich text comment content."
            ),
        ),
        migrations.AlterField(
            model_name="rowcomment",
            name="comment",
            field=models.TextField(
                editable=False, help_text="The users comment.", null=True
            ),
        ),
    ]
