# Generated by Django 3.2.21 on 2023-09-19 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0129_add_unique_constraint_viewfieldoptions"),
        ("baserow_premium", "0013_remove_duplicate_viewfieldoptions"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="calendarviewfieldoptions",
            unique_together={("calendar_view", "field")},
        ),
        migrations.AlterUniqueTogether(
            name="kanbanviewfieldoptions",
            unique_together={("kanban_view", "field")},
        ),
    ]
