# Generated by Django 4.1.13 on 2024-06-07 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0158_field_description"),
        ("baserow_premium", "0017_aifield"),
    ]

    operations = [
        migrations.AddField(
            model_name="aifield",
            name="ai_file_field",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_field",
                to="database.field",
            ),
        ),
    ]
