# Generated by Django 5.0.9 on 2024-09-23 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_premium", "0019_calendarview_ical_slug"),
        ("database", "0163_alter_formulafield_expand_formula_when_referenced"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimelineView",
            fields=[
                (
                    "view_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="database.view",
                    ),
                ),
                (
                    "end_date_field",
                    models.ForeignKey(
                        blank=True,
                        help_text="One of the supported date fields that the timeline view will be use as end date.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timeline_views_end_date_field",
                        to="database.field",
                    ),
                ),
                (
                    "start_date_field",
                    models.ForeignKey(
                        blank=True,
                        help_text="One of the supported date fields that the timeline view will be use as start date.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timeline_views_start_date_field",
                        to="database.field",
                    ),
                ),
            ],
            options={
                "db_table": "database_timelineview",
            },
            bases=("database.view",),
        ),
        migrations.CreateModel(
            name="TimelineViewFieldOptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hidden",
                    models.BooleanField(
                        default=True,
                        help_text="Whether or not the field should be hidden in the card.",
                    ),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        default=32767,
                        help_text="The order that the field has in the view. Lower value is first.",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="database.field"
                    ),
                ),
                (
                    "timeline_view",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="baserow_premium.timelineview",
                    ),
                ),
            ],
            options={
                "db_table": "database_timelineviewfieldoptions",
                "ordering": ("order", "field_id"),
                "unique_together": {("timeline_view", "field")},
            },
        ),
        migrations.AddField(
            model_name="timelineview",
            name="field_options",
            field=models.ManyToManyField(
                through="baserow_premium.TimelineViewFieldOptions", to="database.field"
            ),
        ),
    ]
