# Generated by Django 5.0.9 on 2024-12-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_premium", "0023_aifield_ai_output_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aifield",
            name="ai_generative_ai_model",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
