# Generated by Django 5.0.13 on 2025-06-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_premium", "0026_chartseriesconfig_chartseriesconfig_unique_series"),
    ]

    operations = [
        migrations.AddField(
            model_name="chartwidget",
            name="default_series_chart_type",
            field=models.CharField(
                choices=[("BAR", "Bar"), ("LINE", "Line")],
                db_default="BAR",
                default="BAR",
                help_text="Default chart type.",
                max_length=4,
            ),
        ),
    ]
