# Generated by Django 5.0.13 on 2025-07-23 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_premium", "0027_chartwidget_default_series_chart_type"),
        ("dashboard", "0003_widget_dashboarddatasource_summarywidget"),
    ]

    operations = [
        migrations.CreateModel(
            name="PieChartWidget",
            fields=[
                (
                    "widget_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dashboard.widget",
                    ),
                ),
                (
                    "default_series_chart_type",
                    models.CharField(
                        choices=[("PIE", "Pie"), ("DOUGHNUT", "Doughnut")],
                        db_default="PIE",
                        default="PIE",
                        help_text="Default chart type.",
                        max_length=10,
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        help_text="Data source for fetching the result to display.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dashboard.dashboarddatasource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("dashboard.widget",),
        ),
        migrations.CreateModel(
            name="PieChartSeriesConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "series_chart_type",
                    models.CharField(
                        choices=[("PIE", "Pie"), ("DOUGHNUT", "Doughnut")],
                        default="PIE",
                        help_text="Type of chart to display (Pie, Doughnut).",
                        max_length=10,
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="baserow_premium.localbaserowtableserviceaggregationseries",
                    ),
                ),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series_config",
                        to="baserow_premium.piechartwidget",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="piechartseriesconfig",
            constraint=models.UniqueConstraint(
                fields=("series",), name="pie_chart_unique_series"
            ),
        ),
    ]
