# Generated by Django 3.2.20 on 2023-08-29 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0125_add_row_history"),
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="localbaserowgetrow",
            name="table",
        ),
        migrations.RemoveField(
            model_name="localbaserowlistrows",
            name="table",
        ),
        migrations.AddField(
            model_name="localbaserowgetrow",
            name="view",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="database.view",
            ),
        ),
        migrations.AddField(
            model_name="localbaserowlistrows",
            name="view",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="database.view",
            ),
        ),
    ]
