# Generated by Django 3.2.20 on 2023-09-14 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0126_alter_rowhistory_options"),
        ("integrations", "0003_add_localbaserow_service_search_query"),
    ]

    operations = [
        migrations.AddField(
            model_name="localbaserowgetrow",
            name="table",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="database.table",
            ),
        ),
        migrations.AddField(
            model_name="localbaserowlistrows",
            name="table",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="database.table",
            ),
        ),
    ]
