# Generated by Django 4.0.10 on 2024-01-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "integrations",
            "0004_migrate_local_baserow_getrow_list_rows_search_query_to_formulas",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="localbaserowtableservicefilter",
            name="value_is_formula",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the value is a formula or not.",
            ),
        ),
    ]
