# Generated by Django 3.2.21 on 2023-10-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0006_localbaserowtableservice_filter_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="localbaserowtableservicefilter",
            options={"ordering": ("order", "id")},
        ),
        migrations.AddField(
            model_name="localbaserowtableservicefilter",
            name="order",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
