# Generated by Django 3.2.21 on 2023-10-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0007_localbaserow_filter_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="localbaserowtableservicesort",
            options={"ordering": ("order", "id")},
        ),
        migrations.AddField(
            model_name="localbaserowtableservicesort",
            name="order_by",
            field=models.CharField(
                choices=[("ASC", "Ascending"), ("DESC", "Descending")],
                default="ASC",
                help_text="Indicates the sort order direction. ASC (Ascending) is from A to Z and DESC (Descending) is from Z to A.",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="localbaserowtableservicesort",
            name="order",
            field=models.PositiveIntegerField(),
        ),
    ]
