# Generated by Django 5.0.9 on 2024-10-22 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0090_exportapplicationsjob"),
        ("database", "0170_update_password_tsv_fields"),
        ("integrations", "0009_alter_localbaserowgetrow_search_query_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalBaserowAggregateRows",
            fields=[
                (
                    "service_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.service",
                    ),
                ),
                (
                    "search_query",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The query to apply to the service to narrow the results down.",
                        max_length=225,
                    ),
                ),
                (
                    "filter_type",
                    models.CharField(
                        choices=[("AND", "And"), ("OR", "Or")],
                        default="AND",
                        help_text="Indicates whether all the rows should apply to all filters (AND) or to any filter (OR).",
                        max_length=3,
                    ),
                ),
                (
                    "aggregation_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The field aggregation type.",
                        max_length=48,
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        help_text="The aggregated field.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="database.field",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="database.table",
                    ),
                ),
                (
                    "view",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="database.view",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.service", models.Model),
        ),
    ]
