# Generated by Django 3.2.21 on 2023-11-09 13:58

from django.db import migrations

import baserow.core.formula.field


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0010_local_baserow_upsert_field_mapping_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="localbaserowupsertrow",
            name="row_id",
            field=baserow.core.formula.field.FormulaField(default=None),
            preserve_default=False,
        ),
    ]
