# Generated by Django 5.0.13 on 2025-05-19 15:02

import django.db.models.deletion
from django.db import migrations, models

import baserow.core.formula.field


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0099_mcpendpoint"),
        ("integrations", "0012_localbaserowrowcreated_localbaserowrowupdated"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoreHTTPRequestService",
            fields=[
                (
                    "service_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.service",
                    ),
                ),
                (
                    "http_method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("DELETE", "DELETE"),
                            ("PATCH", "PATCH"),
                            ("HEAD", "HEAD"),
                            ("OPTIONS", "OPTIONS"),
                        ],
                        default="GET",
                        help_text="The HTTP method to use for the request (e.g., GET, POST).",
                        max_length=10,
                    ),
                ),
                (
                    "url",
                    baserow.core.formula.field.FormulaField(
                        blank=True,
                        help_text="The URL to which the HTTP request will be sent.",
                    ),
                ),
                (
                    "body_type",
                    models.CharField(
                        choices=[
                            ("json", "JSON"),
                            ("form", "Form Data"),
                            ("raw", "Raw"),
                            ("none", "None"),
                        ],
                        default="none",
                        help_text="The type of the body content (e.g., JSON, Form Data).",
                        max_length=20,
                    ),
                ),
                (
                    "body_content",
                    baserow.core.formula.field.FormulaField(
                        blank=True,
                        help_text="The content of the body of the HTTP request.",
                    ),
                ),
                (
                    "timeout",
                    models.PositiveIntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="Value cannot be less than 1."
                            ),
                            django.core.validators.MaxValueValidator(
                                120, message="Value cannot be greater than 120."
                            ),
                        ],
                        help_text="The timeout for the HTTP request in seconds.",
                    ),
                ),
                (
                    "response_sample",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="Response got from test.",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.service",),
        ),
        migrations.CreateModel(
            name="HTTPFormData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(help_text="The form data key.", max_length=255),
                ),
                (
                    "value",
                    baserow.core.formula.field.FormulaField(
                        blank=True, help_text="The form data value."
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_data",
                        to="integrations.corehttprequestservice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HTTPHeader",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(help_text="The header key.", max_length=255)),
                (
                    "value",
                    baserow.core.formula.field.FormulaField(
                        blank=True, help_text="The header value."
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="headers",
                        to="integrations.corehttprequestservice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HTTPQueryParam",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="The query parameter key.", max_length=255
                    ),
                ),
                (
                    "value",
                    baserow.core.formula.field.FormulaField(
                        blank=True, help_text="The query parameter value."
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="query_params",
                        to="integrations.corehttprequestservice",
                    ),
                ),
            ],
        ),
    ]
