# Generated by Django 5.0.13 on 2025-05-22 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0099_mcpendpoint"),
        ("database", "0189_alter_tableusageupdate_id_and_more"),
        ("integrations", "0013_corehttprequestservice_formdata_httpheader_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LocalBaserowRowCreated",
            new_name="LocalBaserowRowsCreated",
        ),
        migrations.RenameModel(
            old_name="LocalBaserowRowUpdated",
            new_name="LocalBaserowRowsUpdated",
        ),
        migrations.RemoveField(
            model_name="localbaserowrowsupdated",
            name="row_id",
        ),
        migrations.CreateModel(
            name="LocalBaserowRowsDeleted",
            fields=[
                (
                    "service_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.service",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="database.table",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.service",),
        ),
    ]
