# Generated by Django 5.0.13 on 2025-08-08 13:53

import uuid

import django.db.models.deletion
from django.db import migrations, models

import baserow.core.formula.field


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0101_trashentry_additional_restoration_data"),
        ("integrations", "0016_coresmtpemailservice_smtpintegration"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoreRouterService",
            fields=[
                (
                    "service_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.service",
                    ),
                ),
                (
                    "default_edge_label",
                    models.CharField(
                        blank=True,
                        help_text="The label to apply next to router edge.",
                        max_length=75,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.service",),
        ),
        migrations.CreateModel(
            name="CoreRouterServiceEdge",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.UUIDField(default=uuid.uuid4)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="The label to apply next to router edge.",
                        max_length=75,
                    ),
                ),
                (
                    "order",
                    models.DecimalField(
                        decimal_places=20,
                        default=1,
                        editable=False,
                        help_text="Lowest first.",
                        max_digits=40,
                    ),
                ),
                (
                    "condition",
                    baserow.core.formula.field.FormulaField(
                        help_text="The formula that must evaluate to true for this edge to be followed."
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edges",
                        to="integrations.corerouterservice",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
    ]
