# Generated by Django 5.0.13 on 2025-09-03 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0101_trashentry_additional_restoration_data"),
        ("integrations", "0018_remove_corehttprequestservice_response_sample"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorePeriodicService",
            fields=[
                (
                    "service_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.service",
                    ),
                ),
                (
                    "last_periodic_run",
                    models.DateTimeField(
                        help_text="Timestamp when the service was last executed periodically. This value is used to calculate when it should be run.",
                        null=True,
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("MINUTE", "MINUTE"),
                            ("HOUR", "HOUR"),
                            ("DAY", "DAY"),
                            ("WEEK", "WEEK"),
                            ("MONTH", "MONTH"),
                        ],
                        default=None,
                        help_text="The interval frequency for running the service.",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "minute",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="The minute of the hour when to run (0-59). Required for hourly, daily, weekly, monthly intervals.",
                    ),
                ),
                (
                    "hour",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="The hour of the day when to run (0-23). Required for daily, weekly, monthly intervals.",
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="The day of the week when to run (0=Monday, 6=Sunday). Required for weekly intervals.",
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="The day of the month when to run (1-31). Required for monthly intervals.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.service",),
        ),
    ]
