# Generated by Django 5.2.15 on 2026-07-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0031_corestartworkflowservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreperiodicservice',
            name='timezone',
            field=models.CharField(db_default='UTC', default='UTC', help_text='The IANA timezone that the hour, minute, day of week and day of month are expressed in. The schedule keeps this local time across daylight saving transitions.', max_length=255),
        ),
    ]
