# Generated by Django 5.2.15 on 2026-07-15 14:01

import baserow.contrib.integrations.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_alter_workspaceinvitation_message'),
        ('integrations', '0033_coregotonodeservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreInboundEmailTriggerService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.service')),
                ('token', models.CharField(db_index=True, default=baserow.contrib.integrations.core.models.generate_inbound_email_token, help_text='The localpart of the generated inbound email address.', max_length=32)),
                ('is_public', models.BooleanField(default=False, help_text='Defines whether the service is published or not.')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.service',),
        ),
    ]
