# Generated by Django 2.2.2 on 2019-09-13 12:08

import baserow.core.mixins
import baserow.core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(
                    on_delete=models.SET(
                        baserow.core.models.get_default_application_content_type),
                    related_name='applications', to='contenttypes.ContentType',
                    verbose_name='content type')
                 ),
                ('group', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='core.Group')),
            ],
            options={
                'ordering': ('order',),
            },
            bases=(baserow.core.mixins.OrderableMixin, models.Model),
        ),
    ]
