# Generated by Django 3.2.6 on 2021-11-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_settings_instance_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="trashed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="group",
            name="trashed",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
