# Generated by Django 3.2.6 on 2021-12-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_add_trashed_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="name",
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=160),
        ),
    ]
