# Generated by Django 3.2.6 on 2022-02-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_application_name_squashed_0014_alter_group_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="allow_signups_via_group_invitations",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether invited users can create an account "
                "when signing up, even if allow_new_signups is disabled.",
            ),
        ),
    ]
