# Generated by Django 3.2.12 on 2022-03-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_settings_allow_signups_with_group_invitations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="language",
            field=models.TextField(
                choices=[
                    ("en", "English"),
                    ("fr", "French"),
                    ("nl", "Dutch"),
                    ("de", "German"),
                ],
                default="en",
                help_text="An ISO 639 language code (with optional variant) selected "
                "by the user. Ex: en-GB.",
                max_length=10,
            ),
        ),
    ]
