# Generated by Django 3.2.12 on 2022-05-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_trashentry_extra_description_to_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="action",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="action",
            name="type",
            field=models.TextField(db_index=True),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["updated_on", "id"], name="core_action_updated_63da87_idx"
            ),
        ),
    ]
