# Generated by Django 3.2.12 on 2022-05-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_add_action_updated_on_and_type_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="allow_reset_password",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether users can request a password reset link.",
            ),
        ),
    ]
