# Generated by Django 3.2.13 on 2022-06-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_settings_account_deletion_grace_delay"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="storage_usage",
            field=models.IntegerField(null=True),
        ),
    ]
