# Generated by Django 3.2.13 on 2022-06-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="show_admin_signup_page",
            field=models.BooleanField(
                default=True,
                help_text="Indicates that there are not available admin users in the database, so in the frontend the signup form will be shown instead of the login page.",
            ),
        )
    ]
