# Generated by Django 3.2.13 on 2022-07-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_default_settings_show_admin_signup_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="action_group",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
