# Generated by Django 3.2.13 on 2022-09-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_trashentry_related_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="language",
            field=models.TextField(
                choices=[
                    ("en", "English"),
                    ("fr", "French"),
                    ("nl", "Dutch"),
                    ("de", "German"),
                    ("es", "Spanish"),
                    ("it", "Italian"),
                    ("pl", "Polish"),
                ],
                default="en",
                help_text="An ISO 639 language code (with optional variant) selected "
                "by the user. Ex: en-GB.",
                max_length=10,
            ),
        ),
    ]
