# Generated by Django 3.2.13 on 2022-10-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_add_auth_providers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
