# Generated by Django 3.2.13 on 2022-10-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_operation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupinvitation",
            name="permissions",
            field=models.CharField(
                default="MEMBER",
                help_text=(
                    "The permissions that the user is going to get within the "
                    "group after accepting the invitation."
                ),
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="groupuser",
            name="permissions",
            field=models.CharField(
                default="MEMBER",
                help_text="The permissions that the user has within the group.",
                max_length=32,
            ),
        ),
    ]
