# Generated by Django 3.2.13 on 2022-11-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_remove_permissions_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="storage_usage_updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
