# Generated by Django 3.2.13 on 2022-12-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_group_storage_usage_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="allow_global_group_creation",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether all users can create groups, or just staff.",
            ),
        ),
    ]
