# Generated by Django 3.2.13 on 2023-01-13 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_alter_groupinvitation_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="group",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.group"
            ),
        ),
    ]
