# Generated by Django 3.2.13 on 2023-01-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_action_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="createsnapshotjob",
            name="user_ip_address",
            field=models.GenericIPAddressField(
                help_text="The user IP address.", null=True
            ),
        ),
        migrations.AddField(
            model_name="duplicateapplicationjob",
            name="user_ip_address",
            field=models.GenericIPAddressField(
                help_text="The user IP address.", null=True
            ),
        ),
        migrations.AddField(
            model_name="installtemplatejob",
            name="user_ip_address",
            field=models.GenericIPAddressField(
                help_text="The user IP address.", null=True
            ),
        ),
        migrations.AddField(
            model_name="restoresnapshotjob",
            name="user_ip_address",
            field=models.GenericIPAddressField(
                help_text="The user IP address.", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["-updated_on"], name="core_job_updated_e7a478_idx"
            ),
        ),
    ]
