# Generated by Django 3.2.13 on 2023-02-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_add_ip_address_to_jobs"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="track_group_usage",
            field=models.BooleanField(
                default=False,
                help_text="Runs a job once per day which calculates per group row counts and file storage usage, displayed on the admin group page.",
            ),
        ),
    ]
