# Generated by Django 3.2.13 on 2023-02-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_add_role_usage_columns_to_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="now",
            field=models.DateTimeField(null=True),
        ),
    ]
