# Generated by Django 3.2.13 on 2023-01-16 16:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0095_update_exportjob_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0045_group_now"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Group",
            new_name="Workspace",
        ),
    ]
