# Generated by Django 3.2.13 on 2023-01-16 16:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0046_rename_group_workspace"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GroupUser",
            new_name="WorkspaceUser",
        ),
    ]
