# Generated by Django 3.2.13 on 2023-01-16 16:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0047_rename_groupuser_workspaceuser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workspaceuser",
            old_name="group",
            new_name="workspace",
        ),
        migrations.AlterUniqueTogether(
            name="workspaceuser",
            unique_together={("user", "workspace")},
        ),
    ]
