# Generated by Django 3.2.13 on 2023-01-16 16:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_rename_group_workspaceinvitation_workspace"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="group",
            new_name="workspace",
        ),
    ]
