# Generated by Django 3.2.13 on 2023-02-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0056_migrate_group_trash_item_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="allow_global_workspace_creation",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether all users can create workspaces, or just staff.",
            ),
        ),
    ]
