# Generated by Django 3.2.13 on 2023-02-13 11:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_migrate_allow_global_workspace_creation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settings",
            name="allow_global_group_creation",
        ),
    ]
