# Generated by Django 3.2.13 on 2023-02-13 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0059_remove_settings_allow_global_group_creation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspaceuser",
            name="order",
            field=models.PositiveIntegerField(
                help_text="Unique order that the workspace has for the user."
            ),
        ),
        migrations.AlterField(
            model_name="workspaceuser",
            name="user",
            field=models.ForeignKey(
                help_text="The user that has access to the workspace.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
