# Generated by Django 3.2.13 on 2023-02-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0060_auto_20230213_1354"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="allow_signups_via_workspace_invitations",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether invited users can create an account when signing up, even if allow_new_signups is disabled.",
            ),
        ),
    ]
