# Generated by Django 3.2.13 on 2023-02-13 13:56

from django.db import migrations, models


def forward(apps, schema_editor):
    Settings = apps.get_model("core", "Settings")

    Settings.objects.update(
        allow_signups_via_workspace_invitations=models.F(
            "allow_signups_via_group_invitations"
        )
    )


def backward(apps, schema_editor):
    Settings = apps.get_model("core", "Settings")

    Settings.objects.update(
        allow_signups_via_group_invitations=models.F(
            "allow_signups_via_workspace_invitations"
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0061_settings_allow_signups_via_workspace_invitations"),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
