# Generated by Django 3.2.13 on 2023-02-22 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0063_remove_settings_allow_signups_via_group_invitations"),
    ]

    operations = [
        migrations.RenameField(
            model_name="action",
            old_name="group",
            new_name="workspace",
        ),
    ]
