# Generated by Django 3.2.13 on 2023-02-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0064_rename_group_action_workspace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="name",
            field=models.CharField(max_length=165),
        ),
    ]
