# Generated by Django 3.2.18 on 2023-03-28 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0065_alter_workspace_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="settings",
            old_name="track_group_usage",
            new_name="track_workspace_usage",
        ),
    ]
