# Generated by Django 3.2.21 on 2023-09-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0074_email_notifications_user_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="icon",
            field=models.CharField(
                help_text="The icon class name that can be used for displaying purposes.",
                max_length=32,
            ),
        ),
    ]
