# Generated by Django 3.2.21 on 2023-10-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0075_alter_template_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_password_change",
            field=models.DateTimeField(
                default=None,
                help_text="Timestamp when the user changed their password.",
                null=True,
            ),
        ),
    ]
