# Generated by Django 4.1.13 on 2024-03-12 10:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0082_remove_duplicate_workspace_invitation"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="workspaceinvitation",
            unique_together={("workspace", "email")},
        ),
    ]
