# Generated by Django 4.1.13 on 2024-03-12 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0083_alter_workspaceinvitation_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="co_branding_logo",
            field=models.ForeignKey(
                blank=True,
                help_text="Co-branding logo that's placed next to the Baserow logo (176x29).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.userfile",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="show_baserow_help_request",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether the `We need your help!` message will be shown on the dashboard",
            ),
        ),
    ]
