# Generated by Django 4.1.13 on 2024-04-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0084_settings_co_branding_icon_settings_co_branding_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="generative_ai_models_settings",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
