# Generated by Django 4.1.13 on 2024-04-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0085_workspace_generative_ai_models_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="email_verification",
            field=models.TextField(
                choices=[
                    ("no_verification", "no_verification"),
                    ("recommended", "recommended"),
                    ("enforced", "enforced"),
                ],
                default="no_verification",
                help_text="Controls whether user email addresses have to be verified.",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_verified",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
