# Generated by Django 4.1.13 on 2024-05-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0086_settings_email_verification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="completed_onboarding",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="completed_onboarding",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
