# Generated by Django 4.2.13 on 2024-06-24 14:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0087_userprofile_completed_onboarding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blacklistedtoken",
            name="user",
        ),
    ]
