# Generated by Django 5.0.9 on 2024-11-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0092_alter_userprofile_language"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appauthprovider",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="appauthprovider",
            name="domain",
            field=models.CharField(
                help_text="The email domain registered with this provider.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="appauthprovider",
            name="enabled",
            field=models.BooleanField(
                default=True, help_text="Whether the provider is enabled or not."
            ),
        ),
        migrations.AlterField(
            model_name="authprovidermodel",
            name="domain",
            field=models.CharField(
                help_text="The email domain registered with this provider.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="authprovidermodel",
            name="enabled",
            field=models.BooleanField(
                default=True, help_text="Whether the provider is enabled or not."
            ),
        ),
    ]
