# Generated by Django 5.0.9 on 2025-02-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0093_alter_appauthprovider_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importexportresource",
            name="size",
            field=models.PositiveBigIntegerField(
                default=0, help_text="The size of the resource in bytes."
            ),
        ),
    ]
