# Generated by Django 5.0.9 on 2025-03-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0094_alter_importexportresource_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfile",
            name="image_height",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="userfile",
            name="image_width",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
