# Generated by Django 5.0.9 on 2025-03-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0095_alter_userfile_image_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="open_application",
            field=models.IntegerField(
                help_text="The application ID that must be opened when the template is previewed. If null, then the first will automatically be chosen.",
                null=True,
            ),
        ),
    ]
