# Generated by Django 5.0.13 on 2025-03-31 12:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0096_template_open_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="completed_guided_tours",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                default=["sidebar", "database"],
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="completed_guided_tours",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
