# Generated by Django 5.0.13 on 2025-04-15 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0098_alter_userfile_size"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MCPEndpoint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The human readable name of the MCP endpoint for the user.",
                        max_length=100,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="The unique endpoint key that can be used to authorize for the MCP service.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user that owns the MCP endpoint.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="The workspace that the MCP endpoint belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
