# Generated by Django 5.0.13 on 2025-06-10 19:17

from django.db import migrations
from django.db.models import F, Func, Max, Min, Q, Value


def add_builder_to_completed_guided_tours(apps, schema_editor):
    UserProfile = apps.get_model("core", "UserProfile")

    batch_size = 5000
    id_range = UserProfile.objects.aggregate(min_id=Min("id"), max_id=Max("id"))
    min_id = id_range["min_id"]
    max_id = id_range["max_id"]

    if min_id is None or max_id is None:
        return

    class ArrayAppend(Func):
        function = 'array_append'
        arity = 2

    for batch_start in range(min_id, max_id + 1, batch_size):
        batch_end = batch_start + batch_size
        UserProfile.objects.filter(
            ~Q(completed_guided_tours__contains=['builder']),
            id__gte=batch_start, id__lt=batch_end,
            # Only add builder if the user has already completed the `sidebar` and
            # `database` tour because it could be annoying for those users to go
            # through another tour if they already know the tool.
            completed_guided_tours__contains=['sidebar', 'database'],
        ).update(
            completed_guided_tours=ArrayAppend(F('completed_guided_tours'), Value('builder'))
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0099_mcpendpoint"),
    ]

    operations = [
        migrations.RunPython(add_builder_to_completed_guided_tours, reverse_code=migrations.RunPython.noop),
    ]
