# Generated by Django 5.0.13 on 2025-08-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0100_auto_20250610_1917"),
    ]

    operations = [
        migrations.AddField(
            model_name="trashentry",
            name="additional_restoration_data",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
