# Generated by Django 5.0.13 on 2025-09-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0101_trashentry_additional_restoration_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="sample_data",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Store the sample data used for generating a schema.",
                null=True,
            ),
        ),
    ]
