# Generated by Django 5.0.13 on 2025-09-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0102_service_sample_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="trashentry",
            name="managed",
            field=models.BooleanField(
                default=False,
                help_text="Whether this trash entry is internally managed or not. An internally managed trash entry is one users cannot interact with.",
            ),
        ),
    ]
