# Generated by Django 5.0.13 on 2025-09-30 05:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0103_trashentry_managed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trashentry",
            name="managed",
        ),
    ]
