# Generated by Django 5.0.13 on 2025-09-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0104_remove_trashentry_managed"),
    ]

    operations = [
        migrations.AddField(
            model_name="trashentry",
            name="trash_operation_type",
            field=models.CharField(
                blank=True,
                help_text="Optionally provide the trash operation type associated with this trash entry. The trash operation type gives additional context about how this trash entry was created, and if it has specific restoration requirements.",
                max_length=125,
                null=True,
            ),
        ),
    ]
