# Generated by Django 5.2.15 on 2026-08-04 15:23

import baserow.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_aiproviderfeaturesetting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                ('trashed', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=160)),
                ('role_uid', models.CharField(db_default='MEMBER', default='MEMBER', max_length=32)),
                ('last_active', models.DateTimeField(blank=True, db_default=None, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='core.workspace')),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
    ]
